

#pragma once

#ifndef GO_MOC_445aa6_H
#define GO_MOC_445aa6_H

#include <stdint.h>

#ifdef __cplusplus
class AddressesModel445aa6;
void AddressesModel445aa6_AddressesModel445aa6_QRegisterMetaTypes();
class QAddress445aa6;
void QAddress445aa6_QAddress445aa6_QRegisterMetaTypes();
class QWallet445aa6;
void QWallet445aa6_QWallet445aa6_QRegisterMetaTypes();
class WalletModel445aa6;
void WalletModel445aa6_WalletModel445aa6_QRegisterMetaTypes();
extern "C" {
#endif

struct Moc_PackedString { char* data; long long len; };
struct Moc_PackedList { void* data; long long len; };
struct Moc_PackedString QWallet445aa6_Name(void* ptr);
struct Moc_PackedString QWallet445aa6_NameDefault(void* ptr);
void QWallet445aa6_SetName(void* ptr, struct Moc_PackedString name);
void QWallet445aa6_SetNameDefault(void* ptr, struct Moc_PackedString name);
void QWallet445aa6_ConnectNameChanged(void* ptr);
void QWallet445aa6_DisconnectNameChanged(void* ptr);
void QWallet445aa6_NameChanged(void* ptr, struct Moc_PackedString name);
int QWallet445aa6_EncryptionEnabled(void* ptr);
int QWallet445aa6_EncryptionEnabledDefault(void* ptr);
void QWallet445aa6_SetEncryptionEnabled(void* ptr, int encryptionEnabled);
void QWallet445aa6_SetEncryptionEnabledDefault(void* ptr, int encryptionEnabled);
void QWallet445aa6_ConnectEncryptionEnabledChanged(void* ptr);
void QWallet445aa6_DisconnectEncryptionEnabledChanged(void* ptr);
void QWallet445aa6_EncryptionEnabledChanged(void* ptr, int encryptionEnabled);
unsigned long long QWallet445aa6_Sky(void* ptr);
unsigned long long QWallet445aa6_SkyDefault(void* ptr);
void QWallet445aa6_SetSky(void* ptr, unsigned long long sky);
void QWallet445aa6_SetSkyDefault(void* ptr, unsigned long long sky);
void QWallet445aa6_ConnectSkyChanged(void* ptr);
void QWallet445aa6_DisconnectSkyChanged(void* ptr);
void QWallet445aa6_SkyChanged(void* ptr, unsigned long long sky);
unsigned long long QWallet445aa6_CoinHours(void* ptr);
unsigned long long QWallet445aa6_CoinHoursDefault(void* ptr);
void QWallet445aa6_SetCoinHours(void* ptr, unsigned long long coinHours);
void QWallet445aa6_SetCoinHoursDefault(void* ptr, unsigned long long coinHours);
void QWallet445aa6_ConnectCoinHoursChanged(void* ptr);
void QWallet445aa6_DisconnectCoinHoursChanged(void* ptr);
void QWallet445aa6_CoinHoursChanged(void* ptr, unsigned long long coinHours);
struct Moc_PackedString QWallet445aa6_FileName(void* ptr);
struct Moc_PackedString QWallet445aa6_FileNameDefault(void* ptr);
void QWallet445aa6_SetFileName(void* ptr, struct Moc_PackedString fileName);
void QWallet445aa6_SetFileNameDefault(void* ptr, struct Moc_PackedString fileName);
void QWallet445aa6_ConnectFileNameChanged(void* ptr);
void QWallet445aa6_DisconnectFileNameChanged(void* ptr);
void QWallet445aa6_FileNameChanged(void* ptr, struct Moc_PackedString fileName);
int QWallet445aa6_QWallet445aa6_QRegisterMetaType();
int QWallet445aa6_QWallet445aa6_QRegisterMetaType2(char* typeName);
int QWallet445aa6_QWallet445aa6_QmlRegisterType();
int QWallet445aa6_QWallet445aa6_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
void* QWallet445aa6___children_atList(void* ptr, int i);
void QWallet445aa6___children_setList(void* ptr, void* i);
void* QWallet445aa6___children_newList(void* ptr);
void* QWallet445aa6___dynamicPropertyNames_atList(void* ptr, int i);
void QWallet445aa6___dynamicPropertyNames_setList(void* ptr, void* i);
void* QWallet445aa6___dynamicPropertyNames_newList(void* ptr);
void* QWallet445aa6___findChildren_atList(void* ptr, int i);
void QWallet445aa6___findChildren_setList(void* ptr, void* i);
void* QWallet445aa6___findChildren_newList(void* ptr);
void* QWallet445aa6___findChildren_atList3(void* ptr, int i);
void QWallet445aa6___findChildren_setList3(void* ptr, void* i);
void* QWallet445aa6___findChildren_newList3(void* ptr);
void* QWallet445aa6___qFindChildren_atList2(void* ptr, int i);
void QWallet445aa6___qFindChildren_setList2(void* ptr, void* i);
void* QWallet445aa6___qFindChildren_newList2(void* ptr);
void* QWallet445aa6_NewQWallet(void* parent);
void QWallet445aa6_DestroyQWallet(void* ptr);
void QWallet445aa6_DestroyQWalletDefault(void* ptr);
void QWallet445aa6_ChildEventDefault(void* ptr, void* event);
void QWallet445aa6_ConnectNotifyDefault(void* ptr, void* sign);
void QWallet445aa6_CustomEventDefault(void* ptr, void* event);
void QWallet445aa6_DeleteLaterDefault(void* ptr);
void QWallet445aa6_DisconnectNotifyDefault(void* ptr, void* sign);
char QWallet445aa6_EventDefault(void* ptr, void* e);
char QWallet445aa6_EventFilterDefault(void* ptr, void* watched, void* event);
void QWallet445aa6_TimerEventDefault(void* ptr, void* event);
void WalletModel445aa6_AddWallet(void* ptr, void* v0);
void WalletModel445aa6_EditWallet(void* ptr, int row, struct Moc_PackedString name, char encryptionEnabled, unsigned long long sky, unsigned long long coinHours);
void WalletModel445aa6_RemoveWallet(void* ptr, int row);
void WalletModel445aa6_LoadModel(void* ptr);
struct Moc_PackedList WalletModel445aa6_Roles(void* ptr);
struct Moc_PackedList WalletModel445aa6_RolesDefault(void* ptr);
void WalletModel445aa6_SetRoles(void* ptr, void* roles);
void WalletModel445aa6_SetRolesDefault(void* ptr, void* roles);
void WalletModel445aa6_ConnectRolesChanged(void* ptr);
void WalletModel445aa6_DisconnectRolesChanged(void* ptr);
void WalletModel445aa6_RolesChanged(void* ptr, void* roles);
struct Moc_PackedList WalletModel445aa6_Wallets(void* ptr);
struct Moc_PackedList WalletModel445aa6_WalletsDefault(void* ptr);
void WalletModel445aa6_SetWallets(void* ptr, void* wallets);
void WalletModel445aa6_SetWalletsDefault(void* ptr, void* wallets);
void WalletModel445aa6_ConnectWalletsChanged(void* ptr);
void WalletModel445aa6_DisconnectWalletsChanged(void* ptr);
void WalletModel445aa6_WalletsChanged(void* ptr, void* wallets);
int WalletModel445aa6_Count(void* ptr);
int WalletModel445aa6_CountDefault(void* ptr);
void WalletModel445aa6_SetCount(void* ptr, int count);
void WalletModel445aa6_SetCountDefault(void* ptr, int count);
void WalletModel445aa6_ConnectCountChanged(void* ptr);
void WalletModel445aa6_DisconnectCountChanged(void* ptr);
void WalletModel445aa6_CountChanged(void* ptr, int count);
int WalletModel445aa6_WalletModel445aa6_QRegisterMetaType();
int WalletModel445aa6_WalletModel445aa6_QRegisterMetaType2(char* typeName);
int WalletModel445aa6_WalletModel445aa6_QmlRegisterType();
int WalletModel445aa6_WalletModel445aa6_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
int WalletModel445aa6_____itemData_keyList_atList(void* ptr, int i);
void WalletModel445aa6_____itemData_keyList_setList(void* ptr, int i);
void* WalletModel445aa6_____itemData_keyList_newList(void* ptr);
int WalletModel445aa6_____roleNames_keyList_atList(void* ptr, int i);
void WalletModel445aa6_____roleNames_keyList_setList(void* ptr, int i);
void* WalletModel445aa6_____roleNames_keyList_newList(void* ptr);
int WalletModel445aa6_____setItemData_roles_keyList_atList(void* ptr, int i);
void WalletModel445aa6_____setItemData_roles_keyList_setList(void* ptr, int i);
void* WalletModel445aa6_____setItemData_roles_keyList_newList(void* ptr);
void* WalletModel445aa6___changePersistentIndexList_from_atList(void* ptr, int i);
void WalletModel445aa6___changePersistentIndexList_from_setList(void* ptr, void* i);
void* WalletModel445aa6___changePersistentIndexList_from_newList(void* ptr);
void* WalletModel445aa6___changePersistentIndexList_to_atList(void* ptr, int i);
void WalletModel445aa6___changePersistentIndexList_to_setList(void* ptr, void* i);
void* WalletModel445aa6___changePersistentIndexList_to_newList(void* ptr);
int WalletModel445aa6___dataChanged_roles_atList(void* ptr, int i);
void WalletModel445aa6___dataChanged_roles_setList(void* ptr, int i);
void* WalletModel445aa6___dataChanged_roles_newList(void* ptr);
void* WalletModel445aa6___itemData_atList(void* ptr, int v, int i);
void WalletModel445aa6___itemData_setList(void* ptr, int key, void* i);
void* WalletModel445aa6___itemData_newList(void* ptr);
struct Moc_PackedList WalletModel445aa6___itemData_keyList(void* ptr);
void* WalletModel445aa6___layoutAboutToBeChanged_parents_atList(void* ptr, int i);
void WalletModel445aa6___layoutAboutToBeChanged_parents_setList(void* ptr, void* i);
void* WalletModel445aa6___layoutAboutToBeChanged_parents_newList(void* ptr);
void* WalletModel445aa6___layoutChanged_parents_atList(void* ptr, int i);
void WalletModel445aa6___layoutChanged_parents_setList(void* ptr, void* i);
void* WalletModel445aa6___layoutChanged_parents_newList(void* ptr);
void* WalletModel445aa6___match_atList(void* ptr, int i);
void WalletModel445aa6___match_setList(void* ptr, void* i);
void* WalletModel445aa6___match_newList(void* ptr);
void* WalletModel445aa6___mimeData_indexes_atList(void* ptr, int i);
void WalletModel445aa6___mimeData_indexes_setList(void* ptr, void* i);
void* WalletModel445aa6___mimeData_indexes_newList(void* ptr);
void* WalletModel445aa6___persistentIndexList_atList(void* ptr, int i);
void WalletModel445aa6___persistentIndexList_setList(void* ptr, void* i);
void* WalletModel445aa6___persistentIndexList_newList(void* ptr);
void* WalletModel445aa6___roleNames_atList(void* ptr, int v, int i);
void WalletModel445aa6___roleNames_setList(void* ptr, int key, void* i);
void* WalletModel445aa6___roleNames_newList(void* ptr);
struct Moc_PackedList WalletModel445aa6___roleNames_keyList(void* ptr);
void* WalletModel445aa6___setItemData_roles_atList(void* ptr, int v, int i);
void WalletModel445aa6___setItemData_roles_setList(void* ptr, int key, void* i);
void* WalletModel445aa6___setItemData_roles_newList(void* ptr);
struct Moc_PackedList WalletModel445aa6___setItemData_roles_keyList(void* ptr);
int WalletModel445aa6_____doSetRoleNames_roleNames_keyList_atList(void* ptr, int i);
void WalletModel445aa6_____doSetRoleNames_roleNames_keyList_setList(void* ptr, int i);
void* WalletModel445aa6_____doSetRoleNames_roleNames_keyList_newList(void* ptr);
int WalletModel445aa6_____setRoleNames_roleNames_keyList_atList(void* ptr, int i);
void WalletModel445aa6_____setRoleNames_roleNames_keyList_setList(void* ptr, int i);
void* WalletModel445aa6_____setRoleNames_roleNames_keyList_newList(void* ptr);
void* WalletModel445aa6___children_atList(void* ptr, int i);
void WalletModel445aa6___children_setList(void* ptr, void* i);
void* WalletModel445aa6___children_newList(void* ptr);
void* WalletModel445aa6___dynamicPropertyNames_atList(void* ptr, int i);
void WalletModel445aa6___dynamicPropertyNames_setList(void* ptr, void* i);
void* WalletModel445aa6___dynamicPropertyNames_newList(void* ptr);
void* WalletModel445aa6___findChildren_atList(void* ptr, int i);
void WalletModel445aa6___findChildren_setList(void* ptr, void* i);
void* WalletModel445aa6___findChildren_newList(void* ptr);
void* WalletModel445aa6___findChildren_atList3(void* ptr, int i);
void WalletModel445aa6___findChildren_setList3(void* ptr, void* i);
void* WalletModel445aa6___findChildren_newList3(void* ptr);
void* WalletModel445aa6___qFindChildren_atList2(void* ptr, int i);
void WalletModel445aa6___qFindChildren_setList2(void* ptr, void* i);
void* WalletModel445aa6___qFindChildren_newList2(void* ptr);
void* WalletModel445aa6___roles_atList(void* ptr, int v, int i);
void WalletModel445aa6___roles_setList(void* ptr, int key, void* i);
void* WalletModel445aa6___roles_newList(void* ptr);
struct Moc_PackedList WalletModel445aa6___roles_keyList(void* ptr);
void* WalletModel445aa6___setRoles_roles_atList(void* ptr, int v, int i);
void WalletModel445aa6___setRoles_roles_setList(void* ptr, int key, void* i);
void* WalletModel445aa6___setRoles_roles_newList(void* ptr);
struct Moc_PackedList WalletModel445aa6___setRoles_roles_keyList(void* ptr);
void* WalletModel445aa6___rolesChanged_roles_atList(void* ptr, int v, int i);
void WalletModel445aa6___rolesChanged_roles_setList(void* ptr, int key, void* i);
void* WalletModel445aa6___rolesChanged_roles_newList(void* ptr);
struct Moc_PackedList WalletModel445aa6___rolesChanged_roles_keyList(void* ptr);
void* WalletModel445aa6___wallets_atList(void* ptr, int i);
void WalletModel445aa6___wallets_setList(void* ptr, void* i);
void* WalletModel445aa6___wallets_newList(void* ptr);
void* WalletModel445aa6___setWallets_wallets_atList(void* ptr, int i);
void WalletModel445aa6___setWallets_wallets_setList(void* ptr, void* i);
void* WalletModel445aa6___setWallets_wallets_newList(void* ptr);
void* WalletModel445aa6___walletsChanged_wallets_atList(void* ptr, int i);
void WalletModel445aa6___walletsChanged_wallets_setList(void* ptr, void* i);
void* WalletModel445aa6___walletsChanged_wallets_newList(void* ptr);
int WalletModel445aa6_____roles_keyList_atList(void* ptr, int i);
void WalletModel445aa6_____roles_keyList_setList(void* ptr, int i);
void* WalletModel445aa6_____roles_keyList_newList(void* ptr);
int WalletModel445aa6_____setRoles_roles_keyList_atList(void* ptr, int i);
void WalletModel445aa6_____setRoles_roles_keyList_setList(void* ptr, int i);
void* WalletModel445aa6_____setRoles_roles_keyList_newList(void* ptr);
int WalletModel445aa6_____rolesChanged_roles_keyList_atList(void* ptr, int i);
void WalletModel445aa6_____rolesChanged_roles_keyList_setList(void* ptr, int i);
void* WalletModel445aa6_____rolesChanged_roles_keyList_newList(void* ptr);
void* WalletModel445aa6_NewWalletModel(void* parent);
void WalletModel445aa6_DestroyWalletModel(void* ptr);
void WalletModel445aa6_DestroyWalletModelDefault(void* ptr);
char WalletModel445aa6_DropMimeDataDefault(void* ptr, void* data, long long action, int row, int column, void* parent);
long long WalletModel445aa6_FlagsDefault(void* ptr, void* index);
void* WalletModel445aa6_IndexDefault(void* ptr, int row, int column, void* parent);
void* WalletModel445aa6_SiblingDefault(void* ptr, int row, int column, void* idx);
void* WalletModel445aa6_BuddyDefault(void* ptr, void* index);
char WalletModel445aa6_CanDropMimeDataDefault(void* ptr, void* data, long long action, int row, int column, void* parent);
char WalletModel445aa6_CanFetchMoreDefault(void* ptr, void* parent);
int WalletModel445aa6_ColumnCountDefault(void* ptr, void* parent);
void* WalletModel445aa6_DataDefault(void* ptr, void* index, int role);
void WalletModel445aa6_FetchMoreDefault(void* ptr, void* parent);
char WalletModel445aa6_HasChildrenDefault(void* ptr, void* parent);
void* WalletModel445aa6_HeaderDataDefault(void* ptr, int section, long long orientation, int role);
char WalletModel445aa6_InsertColumnsDefault(void* ptr, int column, int count, void* parent);
char WalletModel445aa6_InsertRowsDefault(void* ptr, int row, int count, void* parent);
struct Moc_PackedList WalletModel445aa6_ItemDataDefault(void* ptr, void* index);
struct Moc_PackedList WalletModel445aa6_MatchDefault(void* ptr, void* start, int role, void* value, int hits, long long flags);
void* WalletModel445aa6_MimeDataDefault(void* ptr, void* indexes);
struct Moc_PackedString WalletModel445aa6_MimeTypesDefault(void* ptr);
char WalletModel445aa6_MoveColumnsDefault(void* ptr, void* sourceParent, int sourceColumn, int count, void* destinationParent, int destinationChild);
char WalletModel445aa6_MoveRowsDefault(void* ptr, void* sourceParent, int sourceRow, int count, void* destinationParent, int destinationChild);
void* WalletModel445aa6_ParentDefault(void* ptr, void* index);
char WalletModel445aa6_RemoveColumnsDefault(void* ptr, int column, int count, void* parent);
char WalletModel445aa6_RemoveRowsDefault(void* ptr, int row, int count, void* parent);
void WalletModel445aa6_ResetInternalDataDefault(void* ptr);
void WalletModel445aa6_RevertDefault(void* ptr);
struct Moc_PackedList WalletModel445aa6_RoleNamesDefault(void* ptr);
int WalletModel445aa6_RowCountDefault(void* ptr, void* parent);
char WalletModel445aa6_SetDataDefault(void* ptr, void* index, void* value, int role);
char WalletModel445aa6_SetHeaderDataDefault(void* ptr, int section, long long orientation, void* value, int role);
char WalletModel445aa6_SetItemDataDefault(void* ptr, void* index, void* roles);
void WalletModel445aa6_SortDefault(void* ptr, int column, long long order);
void* WalletModel445aa6_SpanDefault(void* ptr, void* index);
char WalletModel445aa6_SubmitDefault(void* ptr);
long long WalletModel445aa6_SupportedDragActionsDefault(void* ptr);
long long WalletModel445aa6_SupportedDropActionsDefault(void* ptr);
void WalletModel445aa6_ChildEventDefault(void* ptr, void* event);
void WalletModel445aa6_ConnectNotifyDefault(void* ptr, void* sign);
void WalletModel445aa6_CustomEventDefault(void* ptr, void* event);
void WalletModel445aa6_DeleteLaterDefault(void* ptr);
void WalletModel445aa6_DisconnectNotifyDefault(void* ptr, void* sign);
char WalletModel445aa6_EventDefault(void* ptr, void* e);
char WalletModel445aa6_EventFilterDefault(void* ptr, void* watched, void* event);
void WalletModel445aa6_TimerEventDefault(void* ptr, void* event);
void AddressesModel445aa6_AddAddress(void* ptr, void* v0);
void AddressesModel445aa6_RemoveAddress(void* ptr, int v0);
void AddressesModel445aa6_EditAddress(void* ptr, int v0, struct Moc_PackedString v1, unsigned long long v2, unsigned long long v3);
void AddressesModel445aa6_LoadModel(void* ptr, struct Moc_PackedString v0);
struct Moc_PackedList AddressesModel445aa6_Roles(void* ptr);
struct Moc_PackedList AddressesModel445aa6_RolesDefault(void* ptr);
void AddressesModel445aa6_SetRoles(void* ptr, void* roles);
void AddressesModel445aa6_SetRolesDefault(void* ptr, void* roles);
void AddressesModel445aa6_ConnectRolesChanged(void* ptr);
void AddressesModel445aa6_DisconnectRolesChanged(void* ptr);
void AddressesModel445aa6_RolesChanged(void* ptr, void* roles);
struct Moc_PackedList AddressesModel445aa6_Addresses(void* ptr);
struct Moc_PackedList AddressesModel445aa6_AddressesDefault(void* ptr);
void AddressesModel445aa6_SetAddresses(void* ptr, void* addresses);
void AddressesModel445aa6_SetAddressesDefault(void* ptr, void* addresses);
void AddressesModel445aa6_ConnectAddressesChanged(void* ptr);
void AddressesModel445aa6_DisconnectAddressesChanged(void* ptr);
void AddressesModel445aa6_AddressesChanged(void* ptr, void* addresses);
int AddressesModel445aa6_Loaded(void* ptr);
int AddressesModel445aa6_LoadedDefault(void* ptr);
void AddressesModel445aa6_SetLoaded(void* ptr, int loaded);
void AddressesModel445aa6_SetLoadedDefault(void* ptr, int loaded);
void AddressesModel445aa6_ConnectLoadedChanged(void* ptr);
void AddressesModel445aa6_DisconnectLoadedChanged(void* ptr);
void AddressesModel445aa6_LoadedChanged(void* ptr, int loaded);
int AddressesModel445aa6_AddressesModel445aa6_QRegisterMetaType();
int AddressesModel445aa6_AddressesModel445aa6_QRegisterMetaType2(char* typeName);
int AddressesModel445aa6_AddressesModel445aa6_QmlRegisterType();
int AddressesModel445aa6_AddressesModel445aa6_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
int AddressesModel445aa6_____itemData_keyList_atList(void* ptr, int i);
void AddressesModel445aa6_____itemData_keyList_setList(void* ptr, int i);
void* AddressesModel445aa6_____itemData_keyList_newList(void* ptr);
int AddressesModel445aa6_____roleNames_keyList_atList(void* ptr, int i);
void AddressesModel445aa6_____roleNames_keyList_setList(void* ptr, int i);
void* AddressesModel445aa6_____roleNames_keyList_newList(void* ptr);
int AddressesModel445aa6_____setItemData_roles_keyList_atList(void* ptr, int i);
void AddressesModel445aa6_____setItemData_roles_keyList_setList(void* ptr, int i);
void* AddressesModel445aa6_____setItemData_roles_keyList_newList(void* ptr);
void* AddressesModel445aa6___changePersistentIndexList_from_atList(void* ptr, int i);
void AddressesModel445aa6___changePersistentIndexList_from_setList(void* ptr, void* i);
void* AddressesModel445aa6___changePersistentIndexList_from_newList(void* ptr);
void* AddressesModel445aa6___changePersistentIndexList_to_atList(void* ptr, int i);
void AddressesModel445aa6___changePersistentIndexList_to_setList(void* ptr, void* i);
void* AddressesModel445aa6___changePersistentIndexList_to_newList(void* ptr);
int AddressesModel445aa6___dataChanged_roles_atList(void* ptr, int i);
void AddressesModel445aa6___dataChanged_roles_setList(void* ptr, int i);
void* AddressesModel445aa6___dataChanged_roles_newList(void* ptr);
void* AddressesModel445aa6___itemData_atList(void* ptr, int v, int i);
void AddressesModel445aa6___itemData_setList(void* ptr, int key, void* i);
void* AddressesModel445aa6___itemData_newList(void* ptr);
struct Moc_PackedList AddressesModel445aa6___itemData_keyList(void* ptr);
void* AddressesModel445aa6___layoutAboutToBeChanged_parents_atList(void* ptr, int i);
void AddressesModel445aa6___layoutAboutToBeChanged_parents_setList(void* ptr, void* i);
void* AddressesModel445aa6___layoutAboutToBeChanged_parents_newList(void* ptr);
void* AddressesModel445aa6___layoutChanged_parents_atList(void* ptr, int i);
void AddressesModel445aa6___layoutChanged_parents_setList(void* ptr, void* i);
void* AddressesModel445aa6___layoutChanged_parents_newList(void* ptr);
void* AddressesModel445aa6___match_atList(void* ptr, int i);
void AddressesModel445aa6___match_setList(void* ptr, void* i);
void* AddressesModel445aa6___match_newList(void* ptr);
void* AddressesModel445aa6___mimeData_indexes_atList(void* ptr, int i);
void AddressesModel445aa6___mimeData_indexes_setList(void* ptr, void* i);
void* AddressesModel445aa6___mimeData_indexes_newList(void* ptr);
void* AddressesModel445aa6___persistentIndexList_atList(void* ptr, int i);
void AddressesModel445aa6___persistentIndexList_setList(void* ptr, void* i);
void* AddressesModel445aa6___persistentIndexList_newList(void* ptr);
void* AddressesModel445aa6___roleNames_atList(void* ptr, int v, int i);
void AddressesModel445aa6___roleNames_setList(void* ptr, int key, void* i);
void* AddressesModel445aa6___roleNames_newList(void* ptr);
struct Moc_PackedList AddressesModel445aa6___roleNames_keyList(void* ptr);
void* AddressesModel445aa6___setItemData_roles_atList(void* ptr, int v, int i);
void AddressesModel445aa6___setItemData_roles_setList(void* ptr, int key, void* i);
void* AddressesModel445aa6___setItemData_roles_newList(void* ptr);
struct Moc_PackedList AddressesModel445aa6___setItemData_roles_keyList(void* ptr);
int AddressesModel445aa6_____doSetRoleNames_roleNames_keyList_atList(void* ptr, int i);
void AddressesModel445aa6_____doSetRoleNames_roleNames_keyList_setList(void* ptr, int i);
void* AddressesModel445aa6_____doSetRoleNames_roleNames_keyList_newList(void* ptr);
int AddressesModel445aa6_____setRoleNames_roleNames_keyList_atList(void* ptr, int i);
void AddressesModel445aa6_____setRoleNames_roleNames_keyList_setList(void* ptr, int i);
void* AddressesModel445aa6_____setRoleNames_roleNames_keyList_newList(void* ptr);
void* AddressesModel445aa6___children_atList(void* ptr, int i);
void AddressesModel445aa6___children_setList(void* ptr, void* i);
void* AddressesModel445aa6___children_newList(void* ptr);
void* AddressesModel445aa6___dynamicPropertyNames_atList(void* ptr, int i);
void AddressesModel445aa6___dynamicPropertyNames_setList(void* ptr, void* i);
void* AddressesModel445aa6___dynamicPropertyNames_newList(void* ptr);
void* AddressesModel445aa6___findChildren_atList(void* ptr, int i);
void AddressesModel445aa6___findChildren_setList(void* ptr, void* i);
void* AddressesModel445aa6___findChildren_newList(void* ptr);
void* AddressesModel445aa6___findChildren_atList3(void* ptr, int i);
void AddressesModel445aa6___findChildren_setList3(void* ptr, void* i);
void* AddressesModel445aa6___findChildren_newList3(void* ptr);
void* AddressesModel445aa6___qFindChildren_atList2(void* ptr, int i);
void AddressesModel445aa6___qFindChildren_setList2(void* ptr, void* i);
void* AddressesModel445aa6___qFindChildren_newList2(void* ptr);
void* AddressesModel445aa6___roles_atList(void* ptr, int v, int i);
void AddressesModel445aa6___roles_setList(void* ptr, int key, void* i);
void* AddressesModel445aa6___roles_newList(void* ptr);
struct Moc_PackedList AddressesModel445aa6___roles_keyList(void* ptr);
void* AddressesModel445aa6___setRoles_roles_atList(void* ptr, int v, int i);
void AddressesModel445aa6___setRoles_roles_setList(void* ptr, int key, void* i);
void* AddressesModel445aa6___setRoles_roles_newList(void* ptr);
struct Moc_PackedList AddressesModel445aa6___setRoles_roles_keyList(void* ptr);
void* AddressesModel445aa6___rolesChanged_roles_atList(void* ptr, int v, int i);
void AddressesModel445aa6___rolesChanged_roles_setList(void* ptr, int key, void* i);
void* AddressesModel445aa6___rolesChanged_roles_newList(void* ptr);
struct Moc_PackedList AddressesModel445aa6___rolesChanged_roles_keyList(void* ptr);
void* AddressesModel445aa6___addresses_atList(void* ptr, int i);
void AddressesModel445aa6___addresses_setList(void* ptr, void* i);
void* AddressesModel445aa6___addresses_newList(void* ptr);
void* AddressesModel445aa6___setAddresses_addresses_atList(void* ptr, int i);
void AddressesModel445aa6___setAddresses_addresses_setList(void* ptr, void* i);
void* AddressesModel445aa6___setAddresses_addresses_newList(void* ptr);
void* AddressesModel445aa6___addressesChanged_addresses_atList(void* ptr, int i);
void AddressesModel445aa6___addressesChanged_addresses_setList(void* ptr, void* i);
void* AddressesModel445aa6___addressesChanged_addresses_newList(void* ptr);
int AddressesModel445aa6_____roles_keyList_atList(void* ptr, int i);
void AddressesModel445aa6_____roles_keyList_setList(void* ptr, int i);
void* AddressesModel445aa6_____roles_keyList_newList(void* ptr);
int AddressesModel445aa6_____setRoles_roles_keyList_atList(void* ptr, int i);
void AddressesModel445aa6_____setRoles_roles_keyList_setList(void* ptr, int i);
void* AddressesModel445aa6_____setRoles_roles_keyList_newList(void* ptr);
int AddressesModel445aa6_____rolesChanged_roles_keyList_atList(void* ptr, int i);
void AddressesModel445aa6_____rolesChanged_roles_keyList_setList(void* ptr, int i);
void* AddressesModel445aa6_____rolesChanged_roles_keyList_newList(void* ptr);
void* AddressesModel445aa6_NewAddressesModel(void* parent);
void AddressesModel445aa6_DestroyAddressesModel(void* ptr);
void AddressesModel445aa6_DestroyAddressesModelDefault(void* ptr);
char AddressesModel445aa6_DropMimeDataDefault(void* ptr, void* data, long long action, int row, int column, void* parent);
long long AddressesModel445aa6_FlagsDefault(void* ptr, void* index);
void* AddressesModel445aa6_IndexDefault(void* ptr, int row, int column, void* parent);
void* AddressesModel445aa6_SiblingDefault(void* ptr, int row, int column, void* idx);
void* AddressesModel445aa6_BuddyDefault(void* ptr, void* index);
char AddressesModel445aa6_CanDropMimeDataDefault(void* ptr, void* data, long long action, int row, int column, void* parent);
char AddressesModel445aa6_CanFetchMoreDefault(void* ptr, void* parent);
int AddressesModel445aa6_ColumnCountDefault(void* ptr, void* parent);
void* AddressesModel445aa6_DataDefault(void* ptr, void* index, int role);
void AddressesModel445aa6_FetchMoreDefault(void* ptr, void* parent);
char AddressesModel445aa6_HasChildrenDefault(void* ptr, void* parent);
void* AddressesModel445aa6_HeaderDataDefault(void* ptr, int section, long long orientation, int role);
char AddressesModel445aa6_InsertColumnsDefault(void* ptr, int column, int count, void* parent);
char AddressesModel445aa6_InsertRowsDefault(void* ptr, int row, int count, void* parent);
struct Moc_PackedList AddressesModel445aa6_ItemDataDefault(void* ptr, void* index);
struct Moc_PackedList AddressesModel445aa6_MatchDefault(void* ptr, void* start, int role, void* value, int hits, long long flags);
void* AddressesModel445aa6_MimeDataDefault(void* ptr, void* indexes);
struct Moc_PackedString AddressesModel445aa6_MimeTypesDefault(void* ptr);
char AddressesModel445aa6_MoveColumnsDefault(void* ptr, void* sourceParent, int sourceColumn, int count, void* destinationParent, int destinationChild);
char AddressesModel445aa6_MoveRowsDefault(void* ptr, void* sourceParent, int sourceRow, int count, void* destinationParent, int destinationChild);
void* AddressesModel445aa6_ParentDefault(void* ptr, void* index);
char AddressesModel445aa6_RemoveColumnsDefault(void* ptr, int column, int count, void* parent);
char AddressesModel445aa6_RemoveRowsDefault(void* ptr, int row, int count, void* parent);
void AddressesModel445aa6_ResetInternalDataDefault(void* ptr);
void AddressesModel445aa6_RevertDefault(void* ptr);
struct Moc_PackedList AddressesModel445aa6_RoleNamesDefault(void* ptr);
int AddressesModel445aa6_RowCountDefault(void* ptr, void* parent);
char AddressesModel445aa6_SetDataDefault(void* ptr, void* index, void* value, int role);
char AddressesModel445aa6_SetHeaderDataDefault(void* ptr, int section, long long orientation, void* value, int role);
char AddressesModel445aa6_SetItemDataDefault(void* ptr, void* index, void* roles);
void AddressesModel445aa6_SortDefault(void* ptr, int column, long long order);
void* AddressesModel445aa6_SpanDefault(void* ptr, void* index);
char AddressesModel445aa6_SubmitDefault(void* ptr);
long long AddressesModel445aa6_SupportedDragActionsDefault(void* ptr);
long long AddressesModel445aa6_SupportedDropActionsDefault(void* ptr);
void AddressesModel445aa6_ChildEventDefault(void* ptr, void* event);
void AddressesModel445aa6_ConnectNotifyDefault(void* ptr, void* sign);
void AddressesModel445aa6_CustomEventDefault(void* ptr, void* event);
void AddressesModel445aa6_DeleteLaterDefault(void* ptr);
void AddressesModel445aa6_DisconnectNotifyDefault(void* ptr, void* sign);
char AddressesModel445aa6_EventDefault(void* ptr, void* e);
char AddressesModel445aa6_EventFilterDefault(void* ptr, void* watched, void* event);
void AddressesModel445aa6_TimerEventDefault(void* ptr, void* event);
struct Moc_PackedString QAddress445aa6_Address(void* ptr);
struct Moc_PackedString QAddress445aa6_AddressDefault(void* ptr);
void QAddress445aa6_SetAddress(void* ptr, struct Moc_PackedString address);
void QAddress445aa6_SetAddressDefault(void* ptr, struct Moc_PackedString address);
void QAddress445aa6_ConnectAddressChanged(void* ptr);
void QAddress445aa6_DisconnectAddressChanged(void* ptr);
void QAddress445aa6_AddressChanged(void* ptr, struct Moc_PackedString address);
unsigned long long QAddress445aa6_AddressSky(void* ptr);
unsigned long long QAddress445aa6_AddressSkyDefault(void* ptr);
void QAddress445aa6_SetAddressSky(void* ptr, unsigned long long addressSky);
void QAddress445aa6_SetAddressSkyDefault(void* ptr, unsigned long long addressSky);
void QAddress445aa6_ConnectAddressSkyChanged(void* ptr);
void QAddress445aa6_DisconnectAddressSkyChanged(void* ptr);
void QAddress445aa6_AddressSkyChanged(void* ptr, unsigned long long addressSky);
unsigned long long QAddress445aa6_AddressCoinHours(void* ptr);
unsigned long long QAddress445aa6_AddressCoinHoursDefault(void* ptr);
void QAddress445aa6_SetAddressCoinHours(void* ptr, unsigned long long addressCoinHours);
void QAddress445aa6_SetAddressCoinHoursDefault(void* ptr, unsigned long long addressCoinHours);
void QAddress445aa6_ConnectAddressCoinHoursChanged(void* ptr);
void QAddress445aa6_DisconnectAddressCoinHoursChanged(void* ptr);
void QAddress445aa6_AddressCoinHoursChanged(void* ptr, unsigned long long addressCoinHours);
int QAddress445aa6_QAddress445aa6_QRegisterMetaType();
int QAddress445aa6_QAddress445aa6_QRegisterMetaType2(char* typeName);
int QAddress445aa6_QAddress445aa6_QmlRegisterType();
int QAddress445aa6_QAddress445aa6_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
void* QAddress445aa6___children_atList(void* ptr, int i);
void QAddress445aa6___children_setList(void* ptr, void* i);
void* QAddress445aa6___children_newList(void* ptr);
void* QAddress445aa6___dynamicPropertyNames_atList(void* ptr, int i);
void QAddress445aa6___dynamicPropertyNames_setList(void* ptr, void* i);
void* QAddress445aa6___dynamicPropertyNames_newList(void* ptr);
void* QAddress445aa6___findChildren_atList(void* ptr, int i);
void QAddress445aa6___findChildren_setList(void* ptr, void* i);
void* QAddress445aa6___findChildren_newList(void* ptr);
void* QAddress445aa6___findChildren_atList3(void* ptr, int i);
void QAddress445aa6___findChildren_setList3(void* ptr, void* i);
void* QAddress445aa6___findChildren_newList3(void* ptr);
void* QAddress445aa6___qFindChildren_atList2(void* ptr, int i);
void QAddress445aa6___qFindChildren_setList2(void* ptr, void* i);
void* QAddress445aa6___qFindChildren_newList2(void* ptr);
void* QAddress445aa6_NewQAddress(void* parent);
void QAddress445aa6_DestroyQAddress(void* ptr);
void QAddress445aa6_DestroyQAddressDefault(void* ptr);
void QAddress445aa6_ChildEventDefault(void* ptr, void* event);
void QAddress445aa6_ConnectNotifyDefault(void* ptr, void* sign);
void QAddress445aa6_CustomEventDefault(void* ptr, void* event);
void QAddress445aa6_DeleteLaterDefault(void* ptr);
void QAddress445aa6_DisconnectNotifyDefault(void* ptr, void* sign);
char QAddress445aa6_EventDefault(void* ptr, void* e);
char QAddress445aa6_EventFilterDefault(void* ptr, void* watched, void* event);
void QAddress445aa6_TimerEventDefault(void* ptr, void* event);

#ifdef __cplusplus
}
#endif

#endif