import QtQuick 2.12
import QtQuick.Layouts 1.12
import QtQuick.Controls 2.12

Dialog {
    id: dialogAboutLicense

    modal: true
    title: qsTr("License")
    standardButtons: Dialog.Close

    Flickable {
        id: flickable
        clip: true
        anchors.fill: parent
        contentHeight: licenseContent.height

        Label {
            id: licenseContent
            width: parent.width
            text: licenseText
            wrapMode: Label.Wrap
            onHoveredLinkChanged: {
                mouseAreaLinkHovered.cursorShape = hoveredLink ? Qt.PointingHandCursor : Qt.ArrowCursor
            }
            onLinkActivated: { Qt.openUrlExternally(link) }

            MouseArea {
                id: mouseAreaLinkHovered
                anchors.fill: parent
                acceptedButtons: Qt.NoButton
            }
        } // Label

        ScrollIndicator.vertical: ScrollIndicator {
            parent: about.contentItem
            anchors.top: flickable.top
            anchors.bottom: flickable.bottom
            anchors.right: parent.right
            anchors.rightMargin: -about.rightPadding + 1
        }
    } // Flickable

    property string licenseText: "<p><b>GNU GENERAL PUBLIC LICENSE</b><br>"
                                 + "<i>Version 3, June 2007</i></p>"
                                 + "<br>"
                                 + "<p>Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org><br>"
                                 + "Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.</p>"
                                 + "<br>"
                                 + "<p><b>Preamble</b></p>"
                                 + "<br>"
                                 + "<p>The GNU General Public License is a free, copyleft license for "
                                 + "software and other kinds of works."
                                 + "<br>"
                                 + "<p>The licenses for most software and other practical works are designed "
                                 + "to take away your freedom to share and change the works.  By contrast, "
                                 + "the GNU General Public License is intended to guarantee your freedom to "
                                 + "share and change all versions of a program--to make sure it remains free "
                                 + "software for all its users.  We, the Free Software Foundation, use the "
                                 + "GNU General Public License for most of our software; it applies also to "
                                 + "any other work released this way by its authors.  You can apply it to "
                                 + "your programs, too.</p>"
                                 + "<br>"
                                 + "<p>When we speak of free software, we are referring to freedom, not "
                                 + "price.  Our General Public Licenses are designed to make sure that you "
                                 + "have the freedom to distribute copies of free software (and charge for "
                                 + "this service if you wish), that you receive source code or can get it "
                                 + "if you want it, that you can change the software or use pieces of it "
                                 + "in new free programs, and that you know you can do these things.</p>"
                                 + "<br>"
                                 + "<p>To protect your rights, we need to prevent others from denying you "
                                 + "these rights or asking you to surrender the rights.  Therefore, you have "
                                 + "certain responsibilities if you distribute copies of the software, or if "
                                 + "you modify it: responsibilities to respect the freedom of others.</p>"
                                 + "<br>"
                                 + "<p>For example, if you distribute copies of such a program, whether "
                                 + "gratis or for a fee, you must pass on to the recipients the same "
                                 + "freedoms that you received.  You must make sure that they, too, receive "
                                 + "or can get the source code.  And you must show them these terms so they "
                                 + "know their rights.</p>"
                                 + "<br>"
                                 + "<p>Developers that use the GNU GPL protect your rights with two steps: "
                                 + "(1) assert copyright on the software, and (2) offer you this License "
                                 + "giving you legal permission to copy, distribute and/or modify it.</p>"
                                 + "<br>"
                                 + "<p>For the developers' and authors' protection, the GPL clearly explains "
                                 + "that there is no warranty for this free software.  For both users' and "
                                 + "authors' sake, the GPL requires that modified versions be marked as "
                                 + "changed, so that their problems will not be attributed erroneously to "
                                 + "authors of previous versions.</p>"
                                 + "<br>"
                                 + "<p>Some devices are designed to deny users access to install or run "
                                 + "modified versions of the software inside them, although the manufacturer "
                                 + "can do so.  This is fundamentally incompatible with the aim of "
                                 + "protecting users' freedom to change the software.  The systematic "
                                 + "pattern of such abuse occurs in the area of products for individuals to "
                                 + "use, which is precisely where it is most unacceptable.  Therefore, we "
                                 + "have designed this version of the GPL to prohibit the practice for those "
                                 + "products.  If such problems arise substantially in other domains, we "
                                 + "stand ready to extend this provision to those domains in future versions "
                                 + "of the GPL, as needed to protect the freedom of users.</p>"
                                 + "<br>"
                                 + "<p>Finally, every program is threatened constantly by software patents.  "
                                 + "States should not allow patents to restrict development and use of "
                                 + "software on general-purpose computers, but in those that do, we wish to "
                                 + "avoid the special danger that patents applied to a free program could "
                                 + "make it effectively proprietary.  To prevent this, the GPL assures that "
                                 + "patents cannot be used to render the program non-free.</p>"
                                 + "<br>"
                                 + "<p>The precise terms and conditions for copying, distribution and "
                                 + "modification follow.</p>"
                                 + "<br>"
                                 + "<p><b>TERMS AND CONDITIONS</b></p>"
                                 + "<br>"
                                 + "<p><b>0. Definitions</b></p>"
                                 + "<p>\"This License\" refers to version 3 of the GNU General Public License.</p>"
                                 + "<br>"
                                 + "<p>\"Copyright\" also means copyright-like laws that apply to other kinds of "
                                 + "works, such as semiconductor masks.</p>"
                                 + "<br>"
                                 + "<p>\"The Program\" refers to any copyrightable work licensed under this "
                                 + "License.  Each licensee is addressed as \"you\".  \"Licensees\" and "
                                 + "\"recipients\" may be individuals or organizations.</p>"
                                 + "<br>"
                                 + "<p>To \"modify\" a work means to copy from or adapt all or part of the work "
                                 + "in a fashion requiring copyright permission, other than the making of an "
                                 + "exact copy.  The resulting work is called a \"modified version\" of the "
                                 + "earlier work or a work \"based on\" the earlier work.</p>"
                                 + "<br>"
                                 + "<p><b>1. Source Code</b></p>"
                                 + "<br>"
                                 + "<p>The \"source code\" for a work means the preferred form of the work "
                                 + "for making modifications to it.  \"Object code\" means any non-source "
                                 + "form of a work.</p>"
                                 + "<br>"
                                 + "<p>A \"Standard Interface\" means an interface that either is an official "
                                 + "standard defined by a recognized standards body, or, in the case of"
                                 + "interfaces specified for a particular programming language, one that"
                                 + "is widely used among developers working in that language.</p>"
                                 + "<br>"
                                 + "<p>The \"System Libraries\" of an executable work include anything, other "
                                 + "than the work as a whole, that (a) is included in the normal form of "
                                 + "packaging a Major Component, but which is not part of that Major "
                                 + "Component, and (b) serves only to enable use of the work with that "
                                 + "Major Component, or to implement a Standard Interface for which an "
                                 + "implementation is available to the public in source code form.  A "
                                 + "\"Major Component\", in this context, means a major essential component "
                                 + "(kernel, window system, and so on) of the specific operating system "
                                 + "(if any) on which the executable work runs, or a compiler used to "
                                 + "produce the work, or an object code interpreter used to run it.</p>"
                                 + "<br>"
                                 + "<p>The \"Corresponding Source\" for a work in object code form means all "
                                 + "the source code needed to generate, install, and (for an executable "
                                 + "work) run the object code and to modify the work, including scripts to "
                                 + "control those activities.  However, it does not include the work's "
                                 + "System Libraries, or general-purpose tools or generally available free "
                                 + "programs which are used unmodified in performing those activities but "
                                 + "which are not part of the work.  For example, Corresponding Source "
                                 + "includes interface definition files associated with source files for "
                                 + "the work, and the source code for shared libraries and dynamically "
                                 + "linked subprograms that the work is specifically designed to require, "
                                 + "such as by intimate data communication or control flow between those "
                                 + "subprograms and other parts of the work.</p>"
                                 + "<br>"
                                 + "<p>The Corresponding Source need not include anything that users "
                                 + "can regenerate automatically from other parts of the Corresponding "
                                 + "Source.</p>"
                                 + "<br>"
                                 + "<p>The Corresponding Source for a work in source code form is that "
                                 + "same work.</p>"
                                 + "<br>"
                                 + "<p><b>2. Basics permissions</b></p>"
                                 + "<br>"
                                 + "<p>All rights granted under this License are granted for the term of "
                                 + "copyright on the Program, and are irrevocable provided the stated "
                                 + "conditions are met.  This License explicitly affirms your unlimited "
                                 + "permission to run the unmodified Program.  The output from running a "
                                 + "covered work is covered by this License only if the output, given its "
                                 + "content, constitutes a covered work.  This License acknowledges your "
                                 + "rights of fair use or other equivalent, as provided by copyright law.</p>"
                                 + "<br>"
                                 + "<p>You may make, run and propagate covered works that you do not "
                                 + "convey, without conditions so long as your license otherwise remains "
                                 + "in force.  You may convey covered works to others for the sole purpose "
                                 + "of having them make modifications exclusively for you, or provide you "
                                 + "with facilities for running those works, provided that you comply with "
                                 + "the terms of this License in conveying all material for which you do "
                                 + "not control copyright.  Those thus making or running the covered works "
                                 + "for you must do so exclusively on your behalf, under your direction "
                                 + "and control, on terms that prohibit them from making any copies of "
                                 + "your copyrighted material outside their relationship with you.</p>"
                                 + "<br>"
                                 + "<p>Conveying under any other circumstances is permitted solely under "
                                 + "the conditions stated below.  Sublicensing is not allowed; section 10 "
                                 + "makes it unnecessary.</p>"
                                 + "<br>"
                                 + "<p><b>3. Protecting Users' Legal Rights From Anti-Circumvention Law.</b></p>"
                                 + "<br>"
                                 + "<p>No covered work shall be deemed part of an effective technological "
                                 + "measure under any applicable law fulfilling obligations under article "
                                 + "11 of the WIPO copyright treaty adopted on 20 December 1996, or "
                                 + "similar laws prohibiting or restricting circumvention of such "
                                 + "measures.</p>"
                                 + "<br>"
                                 + "<p>When you convey a covered work, you waive any legal power to forbid "
                                 + "circumvention of technological measures to the extent such circumvention "
                                 + "is effected by exercising rights under this License with respect to "
                                 + "the covered work, and you disclaim any intention to limit operation or "
                                 + "modification of the work as a means of enforcing, against the work's "
                                 + "users, your or third parties' legal rights to forbid circumvention of "
                                 + "technological measures.</p>"
                                 + "<br>"
                                 + "<p><b>4. Conveying Verbatim Copies</b></p>"
                                 + "<br>"
                                 + "<p>You may convey verbatim copies of the Program's source code as you "
                                 + "receive it, in any medium, provided that you conspicuously and "
                                 + "appropriately publish on each copy an appropriate copyright notice; "
                                 + "keep intact all notices stating that this License and any "
                                 + "non-permissive terms added in accord with section 7 apply to the code; "
                                 + "keep intact all notices of the absence of any warranty; and give all "
                                 + "recipients a copy of this License along with the Program.</p>"
                                 + "<br>"
                                 + "<p>You may charge any price or no price for each copy that you convey, "
                                 + "and you may offer support or warranty protection for a fee.</p>"
                                 + "<br>"
                                 + "<p><b>5. Conveying Modified Source Versions</b></p>"
                                 + "<br>"
                                 + "<p>You may convey a work based on the Program, or the modifications to "
                                 + "produce it from the Program, in the form of source code under the "
                                 + "terms of section 4, provided that you also meet all of these conditions:</p>"
                                 + "<br>"


                                 + "<p><i>a)</i> You must cause the modified files to carry prominent notices "
                                 + "stating that you changed the files and the date of any change.</p>"
                                 + "<br>"
                                 + "<p><i>b)</i> You must cause any work that you distribute or publish, that in "
                                 + "whole or in part contains or is derived from the Program or any "
                                 + "part thereof, to be licensed as a whole at no charge to all third "
                                 + "parties under the terms of this License.</p>"
                                 + "<br>"
                                 + "<p><i>c)</i> If the modified program normally reads commands interactively "
                                 + "when run, you must cause it, when started running for such "
                                 + "interactive use in the most ordinary way, to print or display an "
                                 + "announcement including an appropriate copyright notice and a "
                                 + "notice that there is no warranty (or else, saying that you provide "
                                 + "a warranty) and that users may redistribute the program under "
                                 + "these conditions, and telling the user how to view a copy of this "
                                 + "License.  (Exception: if the Program itself is interactive but "
                                 + "does not normally print such an announcement, your work based on "
                                 + "the Program is not required to print an announcement.)</p>"
                                 + "<br>"
                                 + "<p>These requirements apply to the modified work as a whole.  If "
                                 + "identifiable sections of that work are not derived from the Program, "
                                 + "and can be reasonably considered independent and separate works in "
                                 + "themselves, then this License, and its terms, do not apply to those "
                                 + "sections when you distribute them as separate works.  But when you "
                                 + "distribute the same sections as part of a whole which is a work based "
                                 + "on the Program, the distribution of the whole must be on the terms of "
                                 + "this License, whose permissions for other licensees extend to the "
                                 + "entire whole, and thus to each and every part regardless of who wrote it.</p>"
                                 + "<br>"
                                 + "<p>Thus, it is not the intent of this section to claim rights or contest "
                                 + "your rights to work written entirely by you; rather, the intent is to "
                                 + "exercise the right to control the distribution of derivative or "
                                 + "collective works based on the Program.</p>"
                                 + "<br>"
                                 + "<p>In addition, mere aggregation of another work not based on the Program"
                                 + "with the Program (or with a work based on the Program) on a volume of"
                                 + "a storage or distribution medium does not bring the other work under"
                                 + "the scope of this License.</p>"
                                 + "<br>"
                                 + "<p><b>3.</b> You may copy and distribute the Program (or a work based on it, "
                                 + "under Section 2) in object code or executable form under the terms of "
                                 + "Sections 1 and 2 above provided that you also do one of the following:</p> "
                                 + "<br>"
                                 + "<p><i>a)</i> Accompany it with the complete corresponding machine-readable "
                                 + "source code, which must be distributed under the terms of Sections "
                                 + "1 and 2 above on a medium customarily used for software interchange; or,</p>"
                                 + ""
                                 + "<p><i>b)</i> Accompany it with a written offer, valid for at least three "
                                 + "years, to give any third party, for a charge no more than your "
                                 + "cost of physically performing source distribution, a complete "
                                 + "machine-readable copy of the corresponding source code, to be "
                                 + "distributed under the terms of Sections 1 and 2 above on a medium "
                                 + "customarily used for software interchange; or,</p>"
                                 + "<br>"
                                 + "<p><i>c)</i> Accompany it with the information you received as to the offer "
                                 + "to distribute corresponding source code.  (This alternative is "
                                 + "allowed only for noncommercial distribution and only if you "
                                 + "received the program in object code or executable form with such "
                                 + "an offer, in accord with Subsection b above.)</p>"
                                 + "<br>"
                                 + "<p>The source code for a work means the preferred form of the work for "
                                 + "making modifications to it.  For an executable work, complete source "
                                 + "code means all the source code for all modules it contains, plus any "
                                 + "associated interface definition files, plus the scripts used to "
                                 + "control compilation and installation of the executable.  However, as a "
                                 + "special exception, the source code distributed need not include "
                                 + "anything that is normally distributed (in either source or binary "
                                 + "form) with the major components (compiler, kernel, and so on) of the "
                                 + "operating system on which the executable runs, unless that component "
                                 + "itself accompanies the executable.</p>"
                                 + "<br>"
                                 + "<p>If distribution of executable or object code is made by offering "
                                 + "access to copy from a designated place, then offering equivalent "
                                 + "access to copy the source code from the same place counts as "
                                 + "distribution of the source code, even though third parties are not "
                                 + "compelled to copy the source along with the object code.</p>"
                                 + "<br>"
                                 + "<p><b>4.</b> You may not copy, modify, sublicense, or distribute the Program "
                                 + "except as expressly provided under this License.  Any attempt "
                                 + "otherwise to copy, modify, sublicense or distribute the Program is "
                                 + "void, and will automatically terminate your rights under this License. "
                                 + "However, parties who have received copies, or rights, from you under "
                                 + "this License will not have their licenses terminated so long as such "
                                 + "parties remain in full compliance.</p>"
                                 + "<br>"
                                 + "<p><b>5.</b> You are not required to accept this License, since you have not "
                                 + "signed it.  However, nothing else grants you permission to modify or "
                                 + "distribute the Program or its derivative works.  These actions are "
                                 + "prohibited by law if you do not accept this License.  Therefore, by "
                                 + "modifying or distributing the Program (or any work based on the "
                                 + "Program), you indicate your acceptance of this License to do so, and "
                                 + "all its terms and conditions for copying, distributing or modifying "
                                 + "the Program or works based on it.</p>"
                                 + "<br>"
                                 + "<p><b>6.</b> Each time you redistribute the Program (or any work based on the "
                                 + "Program), the recipient automatically receives a license from the "
                                 + "original licensor to copy, distribute or modify the Program subject to "
                                 + "these terms and conditions.  You may not impose any further "
                                 + "restrictions on the recipients' exercise of the rights granted herein. "
                                 + "You are not responsible for enforcing compliance by third parties to "
                                 + "this License.</p>"
                                 + "<br>"
                                 + "<p><b>7.</b> If, as a consequence of a court judgment or allegation of patent "
                                 + "infringement or for any other reason (not limited to patent issues), "
                                 + "conditions are imposed on you (whether by court order, agreement or "
                                 + "otherwise) that contradict the conditions of this License, they do not "
                                 + "excuse you from the conditions of this License.  If you cannot "
                                 + "distribute so as to satisfy simultaneously your obligations under this "
                                 + "License and any other pertinent obligations, then as a consequence you "
                                 + "may not distribute the Program at all.  For example, if a patent "
                                 + "license would not permit royalty-free redistribution of the Program by "
                                 + "all those who receive copies directly or indirectly through you, then "
                                 + "the only way you could satisfy both it and this License would be to "
                                 + "refrain entirely from distribution of the Program.</p>"
                                 + "<br>"
                                 + "<p>If any portion of this section is held invalid or unenforceable under "
                                 + "any particular circumstance, the balance of the section is intended to "
                                 + "apply and the section as a whole is intended to apply in other "
                                 + "circumstances.</p>"
                                 + "<br>"
                                 + "<p>It is not the purpose of this section to induce you to infringe any "
                                 + "patents or other property right claims or to contest validity of any "
                                 + "such claims; this section has the sole purpose of protecting the "
                                 + "integrity of the free software distribution system, which is "
                                 + "implemented by public license practices.  Many people have made "
                                 + "generous contributions to the wide range of software distributed "
                                 + "through that system in reliance on consistent application of that "
                                 + "system; it is up to the author/donor to decide if he or she is willing "
                                 + "to distribute software through any other system and a licensee cannot "
                                 + "impose that choice.</p>"
                                 + "<br>"
                                 + "<p>This section is intended to make thoroughly clear what is believed to "
                                 + "be a consequence of the rest of this License.</p>"
                                 + "<br>"
                                 + "<p><b>8.</b> If the distribution and/or use of the Program is restricted in "
                                 + "certain countries either by patents or by copyrighted interfaces, the "
                                 + "original copyright holder who places the Program under this License "
                                 + "may add an explicit geographical distribution limitation excluding "
                                 + "those countries, so that distribution is permitted only in or among "
                                 + "countries not thus excluded.  In such case, this License incorporates "
                                 + "the limitation as if written in the body of this License.</p>"
                                 + "<br>"
                                 + "<p><b>9.</b> The Free Software Foundation may publish revised and/or new versions "
                                 + "of the General Public License from time to time.  Such new versions will "
                                 + "be similar in spirit to the present version, but may differ in detail to "
                                 + "address new problems or concerns.</p>"
                                 + "<br>"
                                 + "<p>Each version is given a distinguishing version number.  If the Program "
                                 + "specifies a version number of this License which applies to it and \"any "
                                 + "later version\", you have the option of following the terms and conditions "
                                 + "either of that version or of any later version published by the Free "
                                 + "Software Foundation.  If the Program does not specify a version number of "
                                 + "this License, you may choose any version ever published by the Free Software "
                                 + "Foundation.</p"
                                 + "<br>"
                                 + "<p><b>10.</b> If you wish to incorporate parts of the Program into other free "
                                 + "programs whose distribution conditions are different, write to the author "
                                 + "to ask for permission.  For software which is copyrighted by the Free "
                                 + "Software Foundation, write to the Free Software Foundation; we sometimes "
                                 + "make exceptions for this.  Our decision will be guided by the two goals "
                                 + "of preserving the free status of all derivatives of our free software and "
                                 + "of promoting the sharing and reuse of software generally.</p>"
                                 + "<br>"
                                 + "<p><b>NO WARRANTY</b></p>"
                                 + "<br>"
                                 + "<p><b>11.</b> BECAUSE THE PROGRAM IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY "
                                 + "FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW.  EXCEPT WHEN "
                                 + "OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES "
                                 + "PROVIDE THE PROGRAM \"AS IS\" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED "
                                 + "OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF "
                                 + "MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE ENTIRE RISK AS "
                                 + "TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU.  SHOULD THE "
                                 + "PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, "
                                 + "REPAIR OR CORRECTION.</p>"
                                 + "<br>"
                                 + "<p><b>12.</b> IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING "
                                 + "WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY AND/OR "
                                 + "REDISTRIBUTE THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, "
                                 + "INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING "
                                 + "OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED "
                                 + "TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY "
                                 + "YOU OR THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER "
                                 + "PROGRAMS), EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE "
                                 + "POSSIBILITY OF SUCH DAMAGES.<p>"
                                 + "<br>"
                                 + "<p><b>END OF TERMS AND CONDITIONS</b></p>"
                                 + "<br><br>"
                                 + "<p><b>How to Apply These Terms to Your New Programs</b></p>"
                                 + "<br>"
                                 + "<p>If you develop a new program, and you want it to be of the greatest "
                                 + "possible use to the public, the best way to achieve this is to make it "
                                 + "free software which everyone can redistribute and change under these terms.</p>"
                                 + "<br>"
                                 + "<p>To do so, attach the following notices to the program.  It is safest "
                                 + "to attach them to the start of each source file to most effectively "
                                 + "convey the exclusion of warranty; and each file should have at least "
                                 + "the \"copyright\" line and a pointer to where the full notice is found.</p>"
                                 + "<br>"
                                 + "<p><one line to give the program's name and a brief idea of what it does.><br>"
                                 + "<i>Copyright (C) &lt;year&gt;  &lt;name of author&gt;</i></p>"
                                 + "<br>"
                                 + "<p>This program is free software; you can redistribute it and/or modify "
                                 + "it under the terms of the GNU General Public License as published by "
                                 + "the Free Software Foundation; either version 2 of the License, or "
                                 + "(at your option) any later version.</p>"
                                 + "<br>"
                                 + "<p>This program is distributed in the hope that it will be useful, "
                                 + "but WITHOUT ANY WARRANTY; without even the implied warranty of "
                                 + "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the "
                                 + "GNU General Public License for more details.</p>"
                                 + "<br>"
                                 + "<p>You should have received a copy of the GNU General Public License along "
                                 + "with this program; if not, write to the Free Software Foundation, Inc., "
                                 + "51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.</p>"
                                 + "<br>"
                                 + "<p>Also add information on how to contact you by electronic and paper mail.</p>"
                                 + "<br>"
                                 + "<p>If the program is interactive, make it output a short notice like this "
                                 + "when it starts in an interactive mode:</p>"
                                 + "<br>"
                                 + "<p><i>Gnomovision version 69, Copyright (C) year name of author</i><br>"
                                 + "Gnomovision comes with ABSOLUTELY NO WARRANTY; for details type `show w'.<br>"
                                 + "This is free software, and you are welcome to redistribute it "
                                 + "under certain conditions; type `show c' for details.</p>"
                                 + "<br>"
                                 + "<p>The hypothetical commands `show w' and `show c' should show the appropriate "
                                 + "parts of the General Public License.  Of course, the commands you use may "
                                 + "be called something other than `show w' and `show c'; they could even be "
                                 + "mouse-clicks or menu items--whatever suits your program.</p>"
                                 + "<br>"
                                 + "<p>You should also get your employer (if you work as a programmer) or your "
                                 + "school, if any, to sign a \"copyright disclaimer\" for the program, if "
                                 + "necessary.  Here is a sample; alter the names:</p>"
                                 + "<br>"
                                 + "<p><i>Yoyodyne, Inc.</i>, hereby disclaims all copyright interest in the program "
                                 + "`Gnomovision' (which makes passes at compilers) written by James Hacker.</p>"
                                 + "<br>"
                                 + "<p><i>&lt;signature of Ty Coon&gt;, 1 April 1989</i><br>"
                                 + "<i>Ty Coon, President of Vice</i>"
                                 + "<br>"
                                 + "<p>This General Public License does not permit incorporating your program into "
                                 + "proprietary programs.  If your program is a subroutine library, you may "
                                 + "consider it more useful to permit linking proprietary applications with the "
                                 + "library.  If this is what you want to do, use the GNU Lesser General "
                                 + "Public License instead of this License.</p>"
}
