

#pragma once

#ifndef GO_MOC_fb4c44_H
#define GO_MOC_fb4c44_H

#include <stdint.h>

#ifdef __cplusplus
class AddressDetailsfb4c44;
void AddressDetailsfb4c44_AddressDetailsfb4c44_QRegisterMetaTypes();
class AddressListfb4c44;
void AddressListfb4c44_AddressListfb4c44_QRegisterMetaTypes();
extern "C" {
#endif

struct Moc_PackedString { char* data; long long len; };
struct Moc_PackedList { void* data; long long len; };
struct Moc_PackedString AddressDetailsfb4c44_Address(void* ptr);
struct Moc_PackedString AddressDetailsfb4c44_AddressDefault(void* ptr);
void AddressDetailsfb4c44_SetAddress(void* ptr, struct Moc_PackedString address);
void AddressDetailsfb4c44_SetAddressDefault(void* ptr, struct Moc_PackedString address);
void AddressDetailsfb4c44_ConnectAddressChanged(void* ptr);
void AddressDetailsfb4c44_DisconnectAddressChanged(void* ptr);
void AddressDetailsfb4c44_AddressChanged(void* ptr, struct Moc_PackedString address);
struct Moc_PackedString AddressDetailsfb4c44_AddressSky(void* ptr);
struct Moc_PackedString AddressDetailsfb4c44_AddressSkyDefault(void* ptr);
void AddressDetailsfb4c44_SetAddressSky(void* ptr, struct Moc_PackedString addressSky);
void AddressDetailsfb4c44_SetAddressSkyDefault(void* ptr, struct Moc_PackedString addressSky);
void AddressDetailsfb4c44_ConnectAddressSkyChanged(void* ptr);
void AddressDetailsfb4c44_DisconnectAddressSkyChanged(void* ptr);
void AddressDetailsfb4c44_AddressSkyChanged(void* ptr, struct Moc_PackedString addressSky);
struct Moc_PackedString AddressDetailsfb4c44_AddressCoinHours(void* ptr);
struct Moc_PackedString AddressDetailsfb4c44_AddressCoinHoursDefault(void* ptr);
void AddressDetailsfb4c44_SetAddressCoinHours(void* ptr, struct Moc_PackedString addressCoinHours);
void AddressDetailsfb4c44_SetAddressCoinHoursDefault(void* ptr, struct Moc_PackedString addressCoinHours);
void AddressDetailsfb4c44_ConnectAddressCoinHoursChanged(void* ptr);
void AddressDetailsfb4c44_DisconnectAddressCoinHoursChanged(void* ptr);
void AddressDetailsfb4c44_AddressCoinHoursChanged(void* ptr, struct Moc_PackedString addressCoinHours);
int AddressDetailsfb4c44_AddressDetailsfb4c44_QRegisterMetaType();
int AddressDetailsfb4c44_AddressDetailsfb4c44_QRegisterMetaType2(char* typeName);
int AddressDetailsfb4c44_AddressDetailsfb4c44_QmlRegisterType();
int AddressDetailsfb4c44_AddressDetailsfb4c44_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
void* AddressDetailsfb4c44___children_atList(void* ptr, int i);
void AddressDetailsfb4c44___children_setList(void* ptr, void* i);
void* AddressDetailsfb4c44___children_newList(void* ptr);
void* AddressDetailsfb4c44___dynamicPropertyNames_atList(void* ptr, int i);
void AddressDetailsfb4c44___dynamicPropertyNames_setList(void* ptr, void* i);
void* AddressDetailsfb4c44___dynamicPropertyNames_newList(void* ptr);
void* AddressDetailsfb4c44___findChildren_atList(void* ptr, int i);
void AddressDetailsfb4c44___findChildren_setList(void* ptr, void* i);
void* AddressDetailsfb4c44___findChildren_newList(void* ptr);
void* AddressDetailsfb4c44___findChildren_atList3(void* ptr, int i);
void AddressDetailsfb4c44___findChildren_setList3(void* ptr, void* i);
void* AddressDetailsfb4c44___findChildren_newList3(void* ptr);
void* AddressDetailsfb4c44___qFindChildren_atList2(void* ptr, int i);
void AddressDetailsfb4c44___qFindChildren_setList2(void* ptr, void* i);
void* AddressDetailsfb4c44___qFindChildren_newList2(void* ptr);
void* AddressDetailsfb4c44_NewAddressDetails(void* parent);
void AddressDetailsfb4c44_DestroyAddressDetails(void* ptr);
void AddressDetailsfb4c44_DestroyAddressDetailsDefault(void* ptr);
void AddressDetailsfb4c44_ChildEventDefault(void* ptr, void* event);
void AddressDetailsfb4c44_ConnectNotifyDefault(void* ptr, void* sign);
void AddressDetailsfb4c44_CustomEventDefault(void* ptr, void* event);
void AddressDetailsfb4c44_DeleteLaterDefault(void* ptr);
void AddressDetailsfb4c44_DisconnectNotifyDefault(void* ptr, void* sign);
char AddressDetailsfb4c44_EventDefault(void* ptr, void* e);
char AddressDetailsfb4c44_EventFilterDefault(void* ptr, void* watched, void* event);
void AddressDetailsfb4c44_TimerEventDefault(void* ptr, void* event);
void AddressListfb4c44_ConnectAddAddress(void* ptr);
void AddressListfb4c44_DisconnectAddAddress(void* ptr);
void AddressListfb4c44_AddAddress(void* ptr, void* transaction);
void AddressListfb4c44_ConnectRemoveAddress(void* ptr);
void AddressListfb4c44_DisconnectRemoveAddress(void* ptr);
void AddressListfb4c44_RemoveAddress(void* ptr, int index);
struct Moc_PackedList AddressListfb4c44_Roles(void* ptr);
struct Moc_PackedList AddressListfb4c44_RolesDefault(void* ptr);
void AddressListfb4c44_SetRoles(void* ptr, void* roles);
void AddressListfb4c44_SetRolesDefault(void* ptr, void* roles);
void AddressListfb4c44_ConnectRolesChanged(void* ptr);
void AddressListfb4c44_DisconnectRolesChanged(void* ptr);
void AddressListfb4c44_RolesChanged(void* ptr, void* roles);
struct Moc_PackedList AddressListfb4c44_Addresses(void* ptr);
struct Moc_PackedList AddressListfb4c44_AddressesDefault(void* ptr);
void AddressListfb4c44_SetAddresses(void* ptr, void* addresses);
void AddressListfb4c44_SetAddressesDefault(void* ptr, void* addresses);
void AddressListfb4c44_ConnectAddressesChanged(void* ptr);
void AddressListfb4c44_DisconnectAddressesChanged(void* ptr);
void AddressListfb4c44_AddressesChanged(void* ptr, void* addresses);
int AddressListfb4c44_AddressListfb4c44_QRegisterMetaType();
int AddressListfb4c44_AddressListfb4c44_QRegisterMetaType2(char* typeName);
int AddressListfb4c44_AddressListfb4c44_QmlRegisterType();
int AddressListfb4c44_AddressListfb4c44_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
int AddressListfb4c44_____itemData_keyList_atList(void* ptr, int i);
void AddressListfb4c44_____itemData_keyList_setList(void* ptr, int i);
void* AddressListfb4c44_____itemData_keyList_newList(void* ptr);
int AddressListfb4c44_____roleNames_keyList_atList(void* ptr, int i);
void AddressListfb4c44_____roleNames_keyList_setList(void* ptr, int i);
void* AddressListfb4c44_____roleNames_keyList_newList(void* ptr);
int AddressListfb4c44_____setItemData_roles_keyList_atList(void* ptr, int i);
void AddressListfb4c44_____setItemData_roles_keyList_setList(void* ptr, int i);
void* AddressListfb4c44_____setItemData_roles_keyList_newList(void* ptr);
void* AddressListfb4c44___changePersistentIndexList_from_atList(void* ptr, int i);
void AddressListfb4c44___changePersistentIndexList_from_setList(void* ptr, void* i);
void* AddressListfb4c44___changePersistentIndexList_from_newList(void* ptr);
void* AddressListfb4c44___changePersistentIndexList_to_atList(void* ptr, int i);
void AddressListfb4c44___changePersistentIndexList_to_setList(void* ptr, void* i);
void* AddressListfb4c44___changePersistentIndexList_to_newList(void* ptr);
int AddressListfb4c44___dataChanged_roles_atList(void* ptr, int i);
void AddressListfb4c44___dataChanged_roles_setList(void* ptr, int i);
void* AddressListfb4c44___dataChanged_roles_newList(void* ptr);
void* AddressListfb4c44___itemData_atList(void* ptr, int v, int i);
void AddressListfb4c44___itemData_setList(void* ptr, int key, void* i);
void* AddressListfb4c44___itemData_newList(void* ptr);
struct Moc_PackedList AddressListfb4c44___itemData_keyList(void* ptr);
void* AddressListfb4c44___layoutAboutToBeChanged_parents_atList(void* ptr, int i);
void AddressListfb4c44___layoutAboutToBeChanged_parents_setList(void* ptr, void* i);
void* AddressListfb4c44___layoutAboutToBeChanged_parents_newList(void* ptr);
void* AddressListfb4c44___layoutChanged_parents_atList(void* ptr, int i);
void AddressListfb4c44___layoutChanged_parents_setList(void* ptr, void* i);
void* AddressListfb4c44___layoutChanged_parents_newList(void* ptr);
void* AddressListfb4c44___match_atList(void* ptr, int i);
void AddressListfb4c44___match_setList(void* ptr, void* i);
void* AddressListfb4c44___match_newList(void* ptr);
void* AddressListfb4c44___mimeData_indexes_atList(void* ptr, int i);
void AddressListfb4c44___mimeData_indexes_setList(void* ptr, void* i);
void* AddressListfb4c44___mimeData_indexes_newList(void* ptr);
void* AddressListfb4c44___persistentIndexList_atList(void* ptr, int i);
void AddressListfb4c44___persistentIndexList_setList(void* ptr, void* i);
void* AddressListfb4c44___persistentIndexList_newList(void* ptr);
void* AddressListfb4c44___roleNames_atList(void* ptr, int v, int i);
void AddressListfb4c44___roleNames_setList(void* ptr, int key, void* i);
void* AddressListfb4c44___roleNames_newList(void* ptr);
struct Moc_PackedList AddressListfb4c44___roleNames_keyList(void* ptr);
void* AddressListfb4c44___setItemData_roles_atList(void* ptr, int v, int i);
void AddressListfb4c44___setItemData_roles_setList(void* ptr, int key, void* i);
void* AddressListfb4c44___setItemData_roles_newList(void* ptr);
struct Moc_PackedList AddressListfb4c44___setItemData_roles_keyList(void* ptr);
int AddressListfb4c44_____doSetRoleNames_roleNames_keyList_atList(void* ptr, int i);
void AddressListfb4c44_____doSetRoleNames_roleNames_keyList_setList(void* ptr, int i);
void* AddressListfb4c44_____doSetRoleNames_roleNames_keyList_newList(void* ptr);
int AddressListfb4c44_____setRoleNames_roleNames_keyList_atList(void* ptr, int i);
void AddressListfb4c44_____setRoleNames_roleNames_keyList_setList(void* ptr, int i);
void* AddressListfb4c44_____setRoleNames_roleNames_keyList_newList(void* ptr);
void* AddressListfb4c44___children_atList(void* ptr, int i);
void AddressListfb4c44___children_setList(void* ptr, void* i);
void* AddressListfb4c44___children_newList(void* ptr);
void* AddressListfb4c44___dynamicPropertyNames_atList(void* ptr, int i);
void AddressListfb4c44___dynamicPropertyNames_setList(void* ptr, void* i);
void* AddressListfb4c44___dynamicPropertyNames_newList(void* ptr);
void* AddressListfb4c44___findChildren_atList(void* ptr, int i);
void AddressListfb4c44___findChildren_setList(void* ptr, void* i);
void* AddressListfb4c44___findChildren_newList(void* ptr);
void* AddressListfb4c44___findChildren_atList3(void* ptr, int i);
void AddressListfb4c44___findChildren_setList3(void* ptr, void* i);
void* AddressListfb4c44___findChildren_newList3(void* ptr);
void* AddressListfb4c44___qFindChildren_atList2(void* ptr, int i);
void AddressListfb4c44___qFindChildren_setList2(void* ptr, void* i);
void* AddressListfb4c44___qFindChildren_newList2(void* ptr);
void* AddressListfb4c44___roles_atList(void* ptr, int v, int i);
void AddressListfb4c44___roles_setList(void* ptr, int key, void* i);
void* AddressListfb4c44___roles_newList(void* ptr);
struct Moc_PackedList AddressListfb4c44___roles_keyList(void* ptr);
void* AddressListfb4c44___setRoles_roles_atList(void* ptr, int v, int i);
void AddressListfb4c44___setRoles_roles_setList(void* ptr, int key, void* i);
void* AddressListfb4c44___setRoles_roles_newList(void* ptr);
struct Moc_PackedList AddressListfb4c44___setRoles_roles_keyList(void* ptr);
void* AddressListfb4c44___rolesChanged_roles_atList(void* ptr, int v, int i);
void AddressListfb4c44___rolesChanged_roles_setList(void* ptr, int key, void* i);
void* AddressListfb4c44___rolesChanged_roles_newList(void* ptr);
struct Moc_PackedList AddressListfb4c44___rolesChanged_roles_keyList(void* ptr);
void* AddressListfb4c44___addresses_atList(void* ptr, int i);
void AddressListfb4c44___addresses_setList(void* ptr, void* i);
void* AddressListfb4c44___addresses_newList(void* ptr);
void* AddressListfb4c44___setAddresses_addresses_atList(void* ptr, int i);
void AddressListfb4c44___setAddresses_addresses_setList(void* ptr, void* i);
void* AddressListfb4c44___setAddresses_addresses_newList(void* ptr);
void* AddressListfb4c44___addressesChanged_addresses_atList(void* ptr, int i);
void AddressListfb4c44___addressesChanged_addresses_setList(void* ptr, void* i);
void* AddressListfb4c44___addressesChanged_addresses_newList(void* ptr);
int AddressListfb4c44_____roles_keyList_atList(void* ptr, int i);
void AddressListfb4c44_____roles_keyList_setList(void* ptr, int i);
void* AddressListfb4c44_____roles_keyList_newList(void* ptr);
int AddressListfb4c44_____setRoles_roles_keyList_atList(void* ptr, int i);
void AddressListfb4c44_____setRoles_roles_keyList_setList(void* ptr, int i);
void* AddressListfb4c44_____setRoles_roles_keyList_newList(void* ptr);
int AddressListfb4c44_____rolesChanged_roles_keyList_atList(void* ptr, int i);
void AddressListfb4c44_____rolesChanged_roles_keyList_setList(void* ptr, int i);
void* AddressListfb4c44_____rolesChanged_roles_keyList_newList(void* ptr);
void* AddressListfb4c44_NewAddressList(void* parent);
void AddressListfb4c44_DestroyAddressList(void* ptr);
void AddressListfb4c44_DestroyAddressListDefault(void* ptr);
char AddressListfb4c44_DropMimeDataDefault(void* ptr, void* data, long long action, int row, int column, void* parent);
long long AddressListfb4c44_FlagsDefault(void* ptr, void* index);
void* AddressListfb4c44_IndexDefault(void* ptr, int row, int column, void* parent);
void* AddressListfb4c44_SiblingDefault(void* ptr, int row, int column, void* idx);
void* AddressListfb4c44_BuddyDefault(void* ptr, void* index);
char AddressListfb4c44_CanDropMimeDataDefault(void* ptr, void* data, long long action, int row, int column, void* parent);
char AddressListfb4c44_CanFetchMoreDefault(void* ptr, void* parent);
int AddressListfb4c44_ColumnCountDefault(void* ptr, void* parent);
void* AddressListfb4c44_DataDefault(void* ptr, void* index, int role);
void AddressListfb4c44_FetchMoreDefault(void* ptr, void* parent);
char AddressListfb4c44_HasChildrenDefault(void* ptr, void* parent);
void* AddressListfb4c44_HeaderDataDefault(void* ptr, int section, long long orientation, int role);
char AddressListfb4c44_InsertColumnsDefault(void* ptr, int column, int count, void* parent);
char AddressListfb4c44_InsertRowsDefault(void* ptr, int row, int count, void* parent);
struct Moc_PackedList AddressListfb4c44_ItemDataDefault(void* ptr, void* index);
struct Moc_PackedList AddressListfb4c44_MatchDefault(void* ptr, void* start, int role, void* value, int hits, long long flags);
void* AddressListfb4c44_MimeDataDefault(void* ptr, void* indexes);
struct Moc_PackedString AddressListfb4c44_MimeTypesDefault(void* ptr);
char AddressListfb4c44_MoveColumnsDefault(void* ptr, void* sourceParent, int sourceColumn, int count, void* destinationParent, int destinationChild);
char AddressListfb4c44_MoveRowsDefault(void* ptr, void* sourceParent, int sourceRow, int count, void* destinationParent, int destinationChild);
void* AddressListfb4c44_ParentDefault(void* ptr, void* index);
char AddressListfb4c44_RemoveColumnsDefault(void* ptr, int column, int count, void* parent);
char AddressListfb4c44_RemoveRowsDefault(void* ptr, int row, int count, void* parent);
void AddressListfb4c44_ResetInternalDataDefault(void* ptr);
void AddressListfb4c44_RevertDefault(void* ptr);
struct Moc_PackedList AddressListfb4c44_RoleNamesDefault(void* ptr);
int AddressListfb4c44_RowCountDefault(void* ptr, void* parent);
char AddressListfb4c44_SetDataDefault(void* ptr, void* index, void* value, int role);
char AddressListfb4c44_SetHeaderDataDefault(void* ptr, int section, long long orientation, void* value, int role);
char AddressListfb4c44_SetItemDataDefault(void* ptr, void* index, void* roles);
void AddressListfb4c44_SortDefault(void* ptr, int column, long long order);
void* AddressListfb4c44_SpanDefault(void* ptr, void* index);
char AddressListfb4c44_SubmitDefault(void* ptr);
long long AddressListfb4c44_SupportedDragActionsDefault(void* ptr);
long long AddressListfb4c44_SupportedDropActionsDefault(void* ptr);
void AddressListfb4c44_ChildEventDefault(void* ptr, void* event);
void AddressListfb4c44_ConnectNotifyDefault(void* ptr, void* sign);
void AddressListfb4c44_CustomEventDefault(void* ptr, void* event);
void AddressListfb4c44_DeleteLaterDefault(void* ptr);
void AddressListfb4c44_DisconnectNotifyDefault(void* ptr, void* sign);
char AddressListfb4c44_EventDefault(void* ptr, void* e);
char AddressListfb4c44_EventFilterDefault(void* ptr, void* watched, void* event);
void AddressListfb4c44_TimerEventDefault(void* ptr, void* event);

#ifdef __cplusplus
}
#endif

#endif