

#pragma once

#ifndef GO_MOC_268d39_H
#define GO_MOC_268d39_H

#include <stdint.h>

#ifdef __cplusplus
class QWallet268d39;
void QWallet268d39_QWallet268d39_QRegisterMetaTypes();
class WalletModel268d39;
void WalletModel268d39_WalletModel268d39_QRegisterMetaTypes();
extern "C" {
#endif

struct Moc_PackedString { char* data; long long len; };
struct Moc_PackedList { void* data; long long len; };
struct Moc_PackedString QWallet268d39_Name(void* ptr);
struct Moc_PackedString QWallet268d39_NameDefault(void* ptr);
void QWallet268d39_SetName(void* ptr, struct Moc_PackedString name);
void QWallet268d39_SetNameDefault(void* ptr, struct Moc_PackedString name);
void QWallet268d39_ConnectNameChanged(void* ptr);
void QWallet268d39_DisconnectNameChanged(void* ptr);
void QWallet268d39_NameChanged(void* ptr, struct Moc_PackedString name);
int QWallet268d39_EncryptionEnabled(void* ptr);
int QWallet268d39_EncryptionEnabledDefault(void* ptr);
void QWallet268d39_SetEncryptionEnabled(void* ptr, int encryptionEnabled);
void QWallet268d39_SetEncryptionEnabledDefault(void* ptr, int encryptionEnabled);
void QWallet268d39_ConnectEncryptionEnabledChanged(void* ptr);
void QWallet268d39_DisconnectEncryptionEnabledChanged(void* ptr);
void QWallet268d39_EncryptionEnabledChanged(void* ptr, int encryptionEnabled);
int QWallet268d39_Sky(void* ptr);
int QWallet268d39_SkyDefault(void* ptr);
void QWallet268d39_SetSky(void* ptr, int sky);
void QWallet268d39_SetSkyDefault(void* ptr, int sky);
void QWallet268d39_ConnectSkyChanged(void* ptr);
void QWallet268d39_DisconnectSkyChanged(void* ptr);
void QWallet268d39_SkyChanged(void* ptr, int sky);
int QWallet268d39_CoinHours(void* ptr);
int QWallet268d39_CoinHoursDefault(void* ptr);
void QWallet268d39_SetCoinHours(void* ptr, int coinHours);
void QWallet268d39_SetCoinHoursDefault(void* ptr, int coinHours);
void QWallet268d39_ConnectCoinHoursChanged(void* ptr);
void QWallet268d39_DisconnectCoinHoursChanged(void* ptr);
void QWallet268d39_CoinHoursChanged(void* ptr, int coinHours);
int QWallet268d39_QWallet268d39_QRegisterMetaType();
int QWallet268d39_QWallet268d39_QRegisterMetaType2(char* typeName);
int QWallet268d39_QWallet268d39_QmlRegisterType();
int QWallet268d39_QWallet268d39_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
void* QWallet268d39___children_atList(void* ptr, int i);
void QWallet268d39___children_setList(void* ptr, void* i);
void* QWallet268d39___children_newList(void* ptr);
void* QWallet268d39___dynamicPropertyNames_atList(void* ptr, int i);
void QWallet268d39___dynamicPropertyNames_setList(void* ptr, void* i);
void* QWallet268d39___dynamicPropertyNames_newList(void* ptr);
void* QWallet268d39___findChildren_atList(void* ptr, int i);
void QWallet268d39___findChildren_setList(void* ptr, void* i);
void* QWallet268d39___findChildren_newList(void* ptr);
void* QWallet268d39___findChildren_atList3(void* ptr, int i);
void QWallet268d39___findChildren_setList3(void* ptr, void* i);
void* QWallet268d39___findChildren_newList3(void* ptr);
void* QWallet268d39___qFindChildren_atList2(void* ptr, int i);
void QWallet268d39___qFindChildren_setList2(void* ptr, void* i);
void* QWallet268d39___qFindChildren_newList2(void* ptr);
void* QWallet268d39_NewQWallet(void* parent);
void QWallet268d39_DestroyQWallet(void* ptr);
void QWallet268d39_DestroyQWalletDefault(void* ptr);
void QWallet268d39_ChildEventDefault(void* ptr, void* event);
void QWallet268d39_ConnectNotifyDefault(void* ptr, void* sign);
void QWallet268d39_CustomEventDefault(void* ptr, void* event);
void QWallet268d39_DeleteLaterDefault(void* ptr);
void QWallet268d39_DisconnectNotifyDefault(void* ptr, void* sign);
char QWallet268d39_EventDefault(void* ptr, void* e);
char QWallet268d39_EventFilterDefault(void* ptr, void* watched, void* event);
void QWallet268d39_TimerEventDefault(void* ptr, void* event);
void WalletModel268d39_AddWallet(void* ptr, void* v0);
void WalletModel268d39_EditWallet(void* ptr, int row, struct Moc_PackedString name, char encryptionEnabled, int sky, int coinHours);
void WalletModel268d39_RemoveWallet(void* ptr, int row);
void WalletModel268d39_LoadModel(void* ptr);
void WalletModel268d39_TestFunc(void* ptr);
void WalletModel268d39_ConnectCreated(void* ptr);
void WalletModel268d39_DisconnectCreated(void* ptr);
void WalletModel268d39_Created(void* ptr);
struct Moc_PackedList WalletModel268d39_Roles(void* ptr);
struct Moc_PackedList WalletModel268d39_RolesDefault(void* ptr);
void WalletModel268d39_SetRoles(void* ptr, void* roles);
void WalletModel268d39_SetRolesDefault(void* ptr, void* roles);
void WalletModel268d39_ConnectRolesChanged(void* ptr);
void WalletModel268d39_DisconnectRolesChanged(void* ptr);
void WalletModel268d39_RolesChanged(void* ptr, void* roles);
struct Moc_PackedList WalletModel268d39_Wallets(void* ptr);
struct Moc_PackedList WalletModel268d39_WalletsDefault(void* ptr);
void WalletModel268d39_SetWallets(void* ptr, void* wallets);
void WalletModel268d39_SetWalletsDefault(void* ptr, void* wallets);
void WalletModel268d39_ConnectWalletsChanged(void* ptr);
void WalletModel268d39_DisconnectWalletsChanged(void* ptr);
void WalletModel268d39_WalletsChanged(void* ptr, void* wallets);
int WalletModel268d39_WalletModel268d39_QRegisterMetaType();
int WalletModel268d39_WalletModel268d39_QRegisterMetaType2(char* typeName);
int WalletModel268d39_WalletModel268d39_QmlRegisterType();
int WalletModel268d39_WalletModel268d39_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
int WalletModel268d39_____itemData_keyList_atList(void* ptr, int i);
void WalletModel268d39_____itemData_keyList_setList(void* ptr, int i);
void* WalletModel268d39_____itemData_keyList_newList(void* ptr);
int WalletModel268d39_____roleNames_keyList_atList(void* ptr, int i);
void WalletModel268d39_____roleNames_keyList_setList(void* ptr, int i);
void* WalletModel268d39_____roleNames_keyList_newList(void* ptr);
int WalletModel268d39_____setItemData_roles_keyList_atList(void* ptr, int i);
void WalletModel268d39_____setItemData_roles_keyList_setList(void* ptr, int i);
void* WalletModel268d39_____setItemData_roles_keyList_newList(void* ptr);
void* WalletModel268d39___changePersistentIndexList_from_atList(void* ptr, int i);
void WalletModel268d39___changePersistentIndexList_from_setList(void* ptr, void* i);
void* WalletModel268d39___changePersistentIndexList_from_newList(void* ptr);
void* WalletModel268d39___changePersistentIndexList_to_atList(void* ptr, int i);
void WalletModel268d39___changePersistentIndexList_to_setList(void* ptr, void* i);
void* WalletModel268d39___changePersistentIndexList_to_newList(void* ptr);
int WalletModel268d39___dataChanged_roles_atList(void* ptr, int i);
void WalletModel268d39___dataChanged_roles_setList(void* ptr, int i);
void* WalletModel268d39___dataChanged_roles_newList(void* ptr);
void* WalletModel268d39___itemData_atList(void* ptr, int v, int i);
void WalletModel268d39___itemData_setList(void* ptr, int key, void* i);
void* WalletModel268d39___itemData_newList(void* ptr);
struct Moc_PackedList WalletModel268d39___itemData_keyList(void* ptr);
void* WalletModel268d39___layoutAboutToBeChanged_parents_atList(void* ptr, int i);
void WalletModel268d39___layoutAboutToBeChanged_parents_setList(void* ptr, void* i);
void* WalletModel268d39___layoutAboutToBeChanged_parents_newList(void* ptr);
void* WalletModel268d39___layoutChanged_parents_atList(void* ptr, int i);
void WalletModel268d39___layoutChanged_parents_setList(void* ptr, void* i);
void* WalletModel268d39___layoutChanged_parents_newList(void* ptr);
void* WalletModel268d39___match_atList(void* ptr, int i);
void WalletModel268d39___match_setList(void* ptr, void* i);
void* WalletModel268d39___match_newList(void* ptr);
void* WalletModel268d39___mimeData_indexes_atList(void* ptr, int i);
void WalletModel268d39___mimeData_indexes_setList(void* ptr, void* i);
void* WalletModel268d39___mimeData_indexes_newList(void* ptr);
void* WalletModel268d39___persistentIndexList_atList(void* ptr, int i);
void WalletModel268d39___persistentIndexList_setList(void* ptr, void* i);
void* WalletModel268d39___persistentIndexList_newList(void* ptr);
void* WalletModel268d39___roleNames_atList(void* ptr, int v, int i);
void WalletModel268d39___roleNames_setList(void* ptr, int key, void* i);
void* WalletModel268d39___roleNames_newList(void* ptr);
struct Moc_PackedList WalletModel268d39___roleNames_keyList(void* ptr);
void* WalletModel268d39___setItemData_roles_atList(void* ptr, int v, int i);
void WalletModel268d39___setItemData_roles_setList(void* ptr, int key, void* i);
void* WalletModel268d39___setItemData_roles_newList(void* ptr);
struct Moc_PackedList WalletModel268d39___setItemData_roles_keyList(void* ptr);
int WalletModel268d39_____doSetRoleNames_roleNames_keyList_atList(void* ptr, int i);
void WalletModel268d39_____doSetRoleNames_roleNames_keyList_setList(void* ptr, int i);
void* WalletModel268d39_____doSetRoleNames_roleNames_keyList_newList(void* ptr);
int WalletModel268d39_____setRoleNames_roleNames_keyList_atList(void* ptr, int i);
void WalletModel268d39_____setRoleNames_roleNames_keyList_setList(void* ptr, int i);
void* WalletModel268d39_____setRoleNames_roleNames_keyList_newList(void* ptr);
void* WalletModel268d39___children_atList(void* ptr, int i);
void WalletModel268d39___children_setList(void* ptr, void* i);
void* WalletModel268d39___children_newList(void* ptr);
void* WalletModel268d39___dynamicPropertyNames_atList(void* ptr, int i);
void WalletModel268d39___dynamicPropertyNames_setList(void* ptr, void* i);
void* WalletModel268d39___dynamicPropertyNames_newList(void* ptr);
void* WalletModel268d39___findChildren_atList(void* ptr, int i);
void WalletModel268d39___findChildren_setList(void* ptr, void* i);
void* WalletModel268d39___findChildren_newList(void* ptr);
void* WalletModel268d39___findChildren_atList3(void* ptr, int i);
void WalletModel268d39___findChildren_setList3(void* ptr, void* i);
void* WalletModel268d39___findChildren_newList3(void* ptr);
void* WalletModel268d39___qFindChildren_atList2(void* ptr, int i);
void WalletModel268d39___qFindChildren_setList2(void* ptr, void* i);
void* WalletModel268d39___qFindChildren_newList2(void* ptr);
void* WalletModel268d39___roles_atList(void* ptr, int v, int i);
void WalletModel268d39___roles_setList(void* ptr, int key, void* i);
void* WalletModel268d39___roles_newList(void* ptr);
struct Moc_PackedList WalletModel268d39___roles_keyList(void* ptr);
void* WalletModel268d39___setRoles_roles_atList(void* ptr, int v, int i);
void WalletModel268d39___setRoles_roles_setList(void* ptr, int key, void* i);
void* WalletModel268d39___setRoles_roles_newList(void* ptr);
struct Moc_PackedList WalletModel268d39___setRoles_roles_keyList(void* ptr);
void* WalletModel268d39___rolesChanged_roles_atList(void* ptr, int v, int i);
void WalletModel268d39___rolesChanged_roles_setList(void* ptr, int key, void* i);
void* WalletModel268d39___rolesChanged_roles_newList(void* ptr);
struct Moc_PackedList WalletModel268d39___rolesChanged_roles_keyList(void* ptr);
void* WalletModel268d39___wallets_atList(void* ptr, int i);
void WalletModel268d39___wallets_setList(void* ptr, void* i);
void* WalletModel268d39___wallets_newList(void* ptr);
void* WalletModel268d39___setWallets_wallets_atList(void* ptr, int i);
void WalletModel268d39___setWallets_wallets_setList(void* ptr, void* i);
void* WalletModel268d39___setWallets_wallets_newList(void* ptr);
void* WalletModel268d39___walletsChanged_wallets_atList(void* ptr, int i);
void WalletModel268d39___walletsChanged_wallets_setList(void* ptr, void* i);
void* WalletModel268d39___walletsChanged_wallets_newList(void* ptr);
int WalletModel268d39_____roles_keyList_atList(void* ptr, int i);
void WalletModel268d39_____roles_keyList_setList(void* ptr, int i);
void* WalletModel268d39_____roles_keyList_newList(void* ptr);
int WalletModel268d39_____setRoles_roles_keyList_atList(void* ptr, int i);
void WalletModel268d39_____setRoles_roles_keyList_setList(void* ptr, int i);
void* WalletModel268d39_____setRoles_roles_keyList_newList(void* ptr);
int WalletModel268d39_____rolesChanged_roles_keyList_atList(void* ptr, int i);
void WalletModel268d39_____rolesChanged_roles_keyList_setList(void* ptr, int i);
void* WalletModel268d39_____rolesChanged_roles_keyList_newList(void* ptr);
void* WalletModel268d39_NewWalletModel(void* parent);
void WalletModel268d39_DestroyWalletModel(void* ptr);
void WalletModel268d39_DestroyWalletModelDefault(void* ptr);
char WalletModel268d39_DropMimeDataDefault(void* ptr, void* data, long long action, int row, int column, void* parent);
long long WalletModel268d39_FlagsDefault(void* ptr, void* index);
void* WalletModel268d39_IndexDefault(void* ptr, int row, int column, void* parent);
void* WalletModel268d39_SiblingDefault(void* ptr, int row, int column, void* idx);
void* WalletModel268d39_BuddyDefault(void* ptr, void* index);
char WalletModel268d39_CanDropMimeDataDefault(void* ptr, void* data, long long action, int row, int column, void* parent);
char WalletModel268d39_CanFetchMoreDefault(void* ptr, void* parent);
int WalletModel268d39_ColumnCountDefault(void* ptr, void* parent);
void* WalletModel268d39_DataDefault(void* ptr, void* index, int role);
void WalletModel268d39_FetchMoreDefault(void* ptr, void* parent);
char WalletModel268d39_HasChildrenDefault(void* ptr, void* parent);
void* WalletModel268d39_HeaderDataDefault(void* ptr, int section, long long orientation, int role);
char WalletModel268d39_InsertColumnsDefault(void* ptr, int column, int count, void* parent);
char WalletModel268d39_InsertRowsDefault(void* ptr, int row, int count, void* parent);
struct Moc_PackedList WalletModel268d39_ItemDataDefault(void* ptr, void* index);
struct Moc_PackedList WalletModel268d39_MatchDefault(void* ptr, void* start, int role, void* value, int hits, long long flags);
void* WalletModel268d39_MimeDataDefault(void* ptr, void* indexes);
struct Moc_PackedString WalletModel268d39_MimeTypesDefault(void* ptr);
char WalletModel268d39_MoveColumnsDefault(void* ptr, void* sourceParent, int sourceColumn, int count, void* destinationParent, int destinationChild);
char WalletModel268d39_MoveRowsDefault(void* ptr, void* sourceParent, int sourceRow, int count, void* destinationParent, int destinationChild);
void* WalletModel268d39_ParentDefault(void* ptr, void* index);
char WalletModel268d39_RemoveColumnsDefault(void* ptr, int column, int count, void* parent);
char WalletModel268d39_RemoveRowsDefault(void* ptr, int row, int count, void* parent);
void WalletModel268d39_ResetInternalDataDefault(void* ptr);
void WalletModel268d39_RevertDefault(void* ptr);
struct Moc_PackedList WalletModel268d39_RoleNamesDefault(void* ptr);
int WalletModel268d39_RowCountDefault(void* ptr, void* parent);
char WalletModel268d39_SetDataDefault(void* ptr, void* index, void* value, int role);
char WalletModel268d39_SetHeaderDataDefault(void* ptr, int section, long long orientation, void* value, int role);
char WalletModel268d39_SetItemDataDefault(void* ptr, void* index, void* roles);
void WalletModel268d39_SortDefault(void* ptr, int column, long long order);
void* WalletModel268d39_SpanDefault(void* ptr, void* index);
char WalletModel268d39_SubmitDefault(void* ptr);
long long WalletModel268d39_SupportedDragActionsDefault(void* ptr);
long long WalletModel268d39_SupportedDropActionsDefault(void* ptr);
void WalletModel268d39_ChildEventDefault(void* ptr, void* event);
void WalletModel268d39_ConnectNotifyDefault(void* ptr, void* sign);
void WalletModel268d39_CustomEventDefault(void* ptr, void* event);
void WalletModel268d39_DeleteLaterDefault(void* ptr);
void WalletModel268d39_DisconnectNotifyDefault(void* ptr, void* sign);
char WalletModel268d39_EventDefault(void* ptr, void* e);
char WalletModel268d39_EventFilterDefault(void* ptr, void* watched, void* event);
void WalletModel268d39_TimerEventDefault(void* ptr, void* event);

#ifdef __cplusplus
}
#endif

#endif