

#pragma once

#ifndef GO_MOC_611006_H
#define GO_MOC_611006_H

#include <stdint.h>

#ifdef __cplusplus
class QWallet611006;
void QWallet611006_QWallet611006_QRegisterMetaTypes();
class WalletManager611006;
void WalletManager611006_WalletManager611006_QRegisterMetaTypes();
class WalletModel611006;
void WalletModel611006_WalletModel611006_QRegisterMetaTypes();
class AddressesModel611006;
void AddressesModel611006_AddressesModel611006_QRegisterMetaTypes();
class QAddress611006;
void QAddress611006_QAddress611006_QRegisterMetaTypes();
extern "C" {
#endif

struct Moc_PackedString { char* data; long long len; };
struct Moc_PackedList { void* data; long long len; };
void AddressesModel611006_AddAddress(void* ptr, void* v0);
void AddressesModel611006_RemoveAddress(void* ptr, int v0);
void AddressesModel611006_EditAddress(void* ptr, int v0, struct Moc_PackedString v1, int v2, int v3);
void AddressesModel611006_LoadModel(void* ptr, struct Moc_PackedString v0);
struct Moc_PackedList AddressesModel611006_Roles(void* ptr);
struct Moc_PackedList AddressesModel611006_RolesDefault(void* ptr);
void AddressesModel611006_SetRoles(void* ptr, void* roles);
void AddressesModel611006_SetRolesDefault(void* ptr, void* roles);
void AddressesModel611006_ConnectRolesChanged(void* ptr);
void AddressesModel611006_DisconnectRolesChanged(void* ptr);
void AddressesModel611006_RolesChanged(void* ptr, void* roles);
struct Moc_PackedList AddressesModel611006_Addresses(void* ptr);
struct Moc_PackedList AddressesModel611006_AddressesDefault(void* ptr);
void AddressesModel611006_SetAddresses(void* ptr, void* addresses);
void AddressesModel611006_SetAddressesDefault(void* ptr, void* addresses);
void AddressesModel611006_ConnectAddressesChanged(void* ptr);
void AddressesModel611006_DisconnectAddressesChanged(void* ptr);
void AddressesModel611006_AddressesChanged(void* ptr, void* addresses);
int AddressesModel611006_Loaded(void* ptr);
int AddressesModel611006_LoadedDefault(void* ptr);
void AddressesModel611006_SetLoaded(void* ptr, int loaded);
void AddressesModel611006_SetLoadedDefault(void* ptr, int loaded);
void AddressesModel611006_ConnectLoadedChanged(void* ptr);
void AddressesModel611006_DisconnectLoadedChanged(void* ptr);
void AddressesModel611006_LoadedChanged(void* ptr, int loaded);
int AddressesModel611006_AddressesModel611006_QRegisterMetaType();
int AddressesModel611006_AddressesModel611006_QRegisterMetaType2(char* typeName);
int AddressesModel611006_AddressesModel611006_QmlRegisterType();
int AddressesModel611006_AddressesModel611006_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
int AddressesModel611006_____itemData_keyList_atList(void* ptr, int i);
void AddressesModel611006_____itemData_keyList_setList(void* ptr, int i);
void* AddressesModel611006_____itemData_keyList_newList(void* ptr);
int AddressesModel611006_____roleNames_keyList_atList(void* ptr, int i);
void AddressesModel611006_____roleNames_keyList_setList(void* ptr, int i);
void* AddressesModel611006_____roleNames_keyList_newList(void* ptr);
int AddressesModel611006_____setItemData_roles_keyList_atList(void* ptr, int i);
void AddressesModel611006_____setItemData_roles_keyList_setList(void* ptr, int i);
void* AddressesModel611006_____setItemData_roles_keyList_newList(void* ptr);
void* AddressesModel611006___changePersistentIndexList_from_atList(void* ptr, int i);
void AddressesModel611006___changePersistentIndexList_from_setList(void* ptr, void* i);
void* AddressesModel611006___changePersistentIndexList_from_newList(void* ptr);
void* AddressesModel611006___changePersistentIndexList_to_atList(void* ptr, int i);
void AddressesModel611006___changePersistentIndexList_to_setList(void* ptr, void* i);
void* AddressesModel611006___changePersistentIndexList_to_newList(void* ptr);
int AddressesModel611006___dataChanged_roles_atList(void* ptr, int i);
void AddressesModel611006___dataChanged_roles_setList(void* ptr, int i);
void* AddressesModel611006___dataChanged_roles_newList(void* ptr);
void* AddressesModel611006___itemData_atList(void* ptr, int v, int i);
void AddressesModel611006___itemData_setList(void* ptr, int key, void* i);
void* AddressesModel611006___itemData_newList(void* ptr);
struct Moc_PackedList AddressesModel611006___itemData_keyList(void* ptr);
void* AddressesModel611006___layoutAboutToBeChanged_parents_atList(void* ptr, int i);
void AddressesModel611006___layoutAboutToBeChanged_parents_setList(void* ptr, void* i);
void* AddressesModel611006___layoutAboutToBeChanged_parents_newList(void* ptr);
void* AddressesModel611006___layoutChanged_parents_atList(void* ptr, int i);
void AddressesModel611006___layoutChanged_parents_setList(void* ptr, void* i);
void* AddressesModel611006___layoutChanged_parents_newList(void* ptr);
void* AddressesModel611006___match_atList(void* ptr, int i);
void AddressesModel611006___match_setList(void* ptr, void* i);
void* AddressesModel611006___match_newList(void* ptr);
void* AddressesModel611006___mimeData_indexes_atList(void* ptr, int i);
void AddressesModel611006___mimeData_indexes_setList(void* ptr, void* i);
void* AddressesModel611006___mimeData_indexes_newList(void* ptr);
void* AddressesModel611006___persistentIndexList_atList(void* ptr, int i);
void AddressesModel611006___persistentIndexList_setList(void* ptr, void* i);
void* AddressesModel611006___persistentIndexList_newList(void* ptr);
void* AddressesModel611006___roleNames_atList(void* ptr, int v, int i);
void AddressesModel611006___roleNames_setList(void* ptr, int key, void* i);
void* AddressesModel611006___roleNames_newList(void* ptr);
struct Moc_PackedList AddressesModel611006___roleNames_keyList(void* ptr);
void* AddressesModel611006___setItemData_roles_atList(void* ptr, int v, int i);
void AddressesModel611006___setItemData_roles_setList(void* ptr, int key, void* i);
void* AddressesModel611006___setItemData_roles_newList(void* ptr);
struct Moc_PackedList AddressesModel611006___setItemData_roles_keyList(void* ptr);
int AddressesModel611006_____doSetRoleNames_roleNames_keyList_atList(void* ptr, int i);
void AddressesModel611006_____doSetRoleNames_roleNames_keyList_setList(void* ptr, int i);
void* AddressesModel611006_____doSetRoleNames_roleNames_keyList_newList(void* ptr);
int AddressesModel611006_____setRoleNames_roleNames_keyList_atList(void* ptr, int i);
void AddressesModel611006_____setRoleNames_roleNames_keyList_setList(void* ptr, int i);
void* AddressesModel611006_____setRoleNames_roleNames_keyList_newList(void* ptr);
void* AddressesModel611006___children_atList(void* ptr, int i);
void AddressesModel611006___children_setList(void* ptr, void* i);
void* AddressesModel611006___children_newList(void* ptr);
void* AddressesModel611006___dynamicPropertyNames_atList(void* ptr, int i);
void AddressesModel611006___dynamicPropertyNames_setList(void* ptr, void* i);
void* AddressesModel611006___dynamicPropertyNames_newList(void* ptr);
void* AddressesModel611006___findChildren_atList(void* ptr, int i);
void AddressesModel611006___findChildren_setList(void* ptr, void* i);
void* AddressesModel611006___findChildren_newList(void* ptr);
void* AddressesModel611006___findChildren_atList3(void* ptr, int i);
void AddressesModel611006___findChildren_setList3(void* ptr, void* i);
void* AddressesModel611006___findChildren_newList3(void* ptr);
void* AddressesModel611006___qFindChildren_atList2(void* ptr, int i);
void AddressesModel611006___qFindChildren_setList2(void* ptr, void* i);
void* AddressesModel611006___qFindChildren_newList2(void* ptr);
void* AddressesModel611006___roles_atList(void* ptr, int v, int i);
void AddressesModel611006___roles_setList(void* ptr, int key, void* i);
void* AddressesModel611006___roles_newList(void* ptr);
struct Moc_PackedList AddressesModel611006___roles_keyList(void* ptr);
void* AddressesModel611006___setRoles_roles_atList(void* ptr, int v, int i);
void AddressesModel611006___setRoles_roles_setList(void* ptr, int key, void* i);
void* AddressesModel611006___setRoles_roles_newList(void* ptr);
struct Moc_PackedList AddressesModel611006___setRoles_roles_keyList(void* ptr);
void* AddressesModel611006___rolesChanged_roles_atList(void* ptr, int v, int i);
void AddressesModel611006___rolesChanged_roles_setList(void* ptr, int key, void* i);
void* AddressesModel611006___rolesChanged_roles_newList(void* ptr);
struct Moc_PackedList AddressesModel611006___rolesChanged_roles_keyList(void* ptr);
void* AddressesModel611006___addresses_atList(void* ptr, int i);
void AddressesModel611006___addresses_setList(void* ptr, void* i);
void* AddressesModel611006___addresses_newList(void* ptr);
void* AddressesModel611006___setAddresses_addresses_atList(void* ptr, int i);
void AddressesModel611006___setAddresses_addresses_setList(void* ptr, void* i);
void* AddressesModel611006___setAddresses_addresses_newList(void* ptr);
void* AddressesModel611006___addressesChanged_addresses_atList(void* ptr, int i);
void AddressesModel611006___addressesChanged_addresses_setList(void* ptr, void* i);
void* AddressesModel611006___addressesChanged_addresses_newList(void* ptr);
int AddressesModel611006_____roles_keyList_atList(void* ptr, int i);
void AddressesModel611006_____roles_keyList_setList(void* ptr, int i);
void* AddressesModel611006_____roles_keyList_newList(void* ptr);
int AddressesModel611006_____setRoles_roles_keyList_atList(void* ptr, int i);
void AddressesModel611006_____setRoles_roles_keyList_setList(void* ptr, int i);
void* AddressesModel611006_____setRoles_roles_keyList_newList(void* ptr);
int AddressesModel611006_____rolesChanged_roles_keyList_atList(void* ptr, int i);
void AddressesModel611006_____rolesChanged_roles_keyList_setList(void* ptr, int i);
void* AddressesModel611006_____rolesChanged_roles_keyList_newList(void* ptr);
void* AddressesModel611006_NewAddressesModel(void* parent);
void AddressesModel611006_DestroyAddressesModel(void* ptr);
void AddressesModel611006_DestroyAddressesModelDefault(void* ptr);
char AddressesModel611006_DropMimeDataDefault(void* ptr, void* data, long long action, int row, int column, void* parent);
long long AddressesModel611006_FlagsDefault(void* ptr, void* index);
void* AddressesModel611006_IndexDefault(void* ptr, int row, int column, void* parent);
void* AddressesModel611006_SiblingDefault(void* ptr, int row, int column, void* idx);
void* AddressesModel611006_BuddyDefault(void* ptr, void* index);
char AddressesModel611006_CanDropMimeDataDefault(void* ptr, void* data, long long action, int row, int column, void* parent);
char AddressesModel611006_CanFetchMoreDefault(void* ptr, void* parent);
int AddressesModel611006_ColumnCountDefault(void* ptr, void* parent);
void* AddressesModel611006_DataDefault(void* ptr, void* index, int role);
void AddressesModel611006_FetchMoreDefault(void* ptr, void* parent);
char AddressesModel611006_HasChildrenDefault(void* ptr, void* parent);
void* AddressesModel611006_HeaderDataDefault(void* ptr, int section, long long orientation, int role);
char AddressesModel611006_InsertColumnsDefault(void* ptr, int column, int count, void* parent);
char AddressesModel611006_InsertRowsDefault(void* ptr, int row, int count, void* parent);
struct Moc_PackedList AddressesModel611006_ItemDataDefault(void* ptr, void* index);
struct Moc_PackedList AddressesModel611006_MatchDefault(void* ptr, void* start, int role, void* value, int hits, long long flags);
void* AddressesModel611006_MimeDataDefault(void* ptr, void* indexes);
struct Moc_PackedString AddressesModel611006_MimeTypesDefault(void* ptr);
char AddressesModel611006_MoveColumnsDefault(void* ptr, void* sourceParent, int sourceColumn, int count, void* destinationParent, int destinationChild);
char AddressesModel611006_MoveRowsDefault(void* ptr, void* sourceParent, int sourceRow, int count, void* destinationParent, int destinationChild);
void* AddressesModel611006_ParentDefault(void* ptr, void* index);
char AddressesModel611006_RemoveColumnsDefault(void* ptr, int column, int count, void* parent);
char AddressesModel611006_RemoveRowsDefault(void* ptr, int row, int count, void* parent);
void AddressesModel611006_ResetInternalDataDefault(void* ptr);
void AddressesModel611006_RevertDefault(void* ptr);
struct Moc_PackedList AddressesModel611006_RoleNamesDefault(void* ptr);
int AddressesModel611006_RowCountDefault(void* ptr, void* parent);
char AddressesModel611006_SetDataDefault(void* ptr, void* index, void* value, int role);
char AddressesModel611006_SetHeaderDataDefault(void* ptr, int section, long long orientation, void* value, int role);
char AddressesModel611006_SetItemDataDefault(void* ptr, void* index, void* roles);
void AddressesModel611006_SortDefault(void* ptr, int column, long long order);
void* AddressesModel611006_SpanDefault(void* ptr, void* index);
char AddressesModel611006_SubmitDefault(void* ptr);
long long AddressesModel611006_SupportedDragActionsDefault(void* ptr);
long long AddressesModel611006_SupportedDropActionsDefault(void* ptr);
void AddressesModel611006_ChildEventDefault(void* ptr, void* event);
void AddressesModel611006_ConnectNotifyDefault(void* ptr, void* sign);
void AddressesModel611006_CustomEventDefault(void* ptr, void* event);
void AddressesModel611006_DeleteLaterDefault(void* ptr);
void AddressesModel611006_DisconnectNotifyDefault(void* ptr, void* sign);
char AddressesModel611006_EventDefault(void* ptr, void* e);
char AddressesModel611006_EventFilterDefault(void* ptr, void* watched, void* event);
void AddressesModel611006_TimerEventDefault(void* ptr, void* event);
struct Moc_PackedString QAddress611006_Address(void* ptr);
struct Moc_PackedString QAddress611006_AddressDefault(void* ptr);
void QAddress611006_SetAddress(void* ptr, struct Moc_PackedString address);
void QAddress611006_SetAddressDefault(void* ptr, struct Moc_PackedString address);
void QAddress611006_ConnectAddressChanged(void* ptr);
void QAddress611006_DisconnectAddressChanged(void* ptr);
void QAddress611006_AddressChanged(void* ptr, struct Moc_PackedString address);
int QAddress611006_AddressSky(void* ptr);
int QAddress611006_AddressSkyDefault(void* ptr);
void QAddress611006_SetAddressSky(void* ptr, int addressSky);
void QAddress611006_SetAddressSkyDefault(void* ptr, int addressSky);
void QAddress611006_ConnectAddressSkyChanged(void* ptr);
void QAddress611006_DisconnectAddressSkyChanged(void* ptr);
void QAddress611006_AddressSkyChanged(void* ptr, int addressSky);
int QAddress611006_AddressCoinHours(void* ptr);
int QAddress611006_AddressCoinHoursDefault(void* ptr);
void QAddress611006_SetAddressCoinHours(void* ptr, int addressCoinHours);
void QAddress611006_SetAddressCoinHoursDefault(void* ptr, int addressCoinHours);
void QAddress611006_ConnectAddressCoinHoursChanged(void* ptr);
void QAddress611006_DisconnectAddressCoinHoursChanged(void* ptr);
void QAddress611006_AddressCoinHoursChanged(void* ptr, int addressCoinHours);
int QAddress611006_QAddress611006_QRegisterMetaType();
int QAddress611006_QAddress611006_QRegisterMetaType2(char* typeName);
int QAddress611006_QAddress611006_QmlRegisterType();
int QAddress611006_QAddress611006_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
void* QAddress611006___children_atList(void* ptr, int i);
void QAddress611006___children_setList(void* ptr, void* i);
void* QAddress611006___children_newList(void* ptr);
void* QAddress611006___dynamicPropertyNames_atList(void* ptr, int i);
void QAddress611006___dynamicPropertyNames_setList(void* ptr, void* i);
void* QAddress611006___dynamicPropertyNames_newList(void* ptr);
void* QAddress611006___findChildren_atList(void* ptr, int i);
void QAddress611006___findChildren_setList(void* ptr, void* i);
void* QAddress611006___findChildren_newList(void* ptr);
void* QAddress611006___findChildren_atList3(void* ptr, int i);
void QAddress611006___findChildren_setList3(void* ptr, void* i);
void* QAddress611006___findChildren_newList3(void* ptr);
void* QAddress611006___qFindChildren_atList2(void* ptr, int i);
void QAddress611006___qFindChildren_setList2(void* ptr, void* i);
void* QAddress611006___qFindChildren_newList2(void* ptr);
void* QAddress611006_NewQAddress(void* parent);
void QAddress611006_DestroyQAddress(void* ptr);
void QAddress611006_DestroyQAddressDefault(void* ptr);
void QAddress611006_ChildEventDefault(void* ptr, void* event);
void QAddress611006_ConnectNotifyDefault(void* ptr, void* sign);
void QAddress611006_CustomEventDefault(void* ptr, void* event);
void QAddress611006_DeleteLaterDefault(void* ptr);
void QAddress611006_DisconnectNotifyDefault(void* ptr, void* sign);
char QAddress611006_EventDefault(void* ptr, void* e);
char QAddress611006_EventFilterDefault(void* ptr, void* watched, void* event);
void QAddress611006_TimerEventDefault(void* ptr, void* event);
struct Moc_PackedString QWallet611006_Name(void* ptr);
struct Moc_PackedString QWallet611006_NameDefault(void* ptr);
void QWallet611006_SetName(void* ptr, struct Moc_PackedString name);
void QWallet611006_SetNameDefault(void* ptr, struct Moc_PackedString name);
void QWallet611006_ConnectNameChanged(void* ptr);
void QWallet611006_DisconnectNameChanged(void* ptr);
void QWallet611006_NameChanged(void* ptr, struct Moc_PackedString name);
int QWallet611006_EncryptionEnabled(void* ptr);
int QWallet611006_EncryptionEnabledDefault(void* ptr);
void QWallet611006_SetEncryptionEnabled(void* ptr, int encryptionEnabled);
void QWallet611006_SetEncryptionEnabledDefault(void* ptr, int encryptionEnabled);
void QWallet611006_ConnectEncryptionEnabledChanged(void* ptr);
void QWallet611006_DisconnectEncryptionEnabledChanged(void* ptr);
void QWallet611006_EncryptionEnabledChanged(void* ptr, int encryptionEnabled);
int QWallet611006_Sky(void* ptr);
int QWallet611006_SkyDefault(void* ptr);
void QWallet611006_SetSky(void* ptr, int sky);
void QWallet611006_SetSkyDefault(void* ptr, int sky);
void QWallet611006_ConnectSkyChanged(void* ptr);
void QWallet611006_DisconnectSkyChanged(void* ptr);
void QWallet611006_SkyChanged(void* ptr, int sky);
int QWallet611006_CoinHours(void* ptr);
int QWallet611006_CoinHoursDefault(void* ptr);
void QWallet611006_SetCoinHours(void* ptr, int coinHours);
void QWallet611006_SetCoinHoursDefault(void* ptr, int coinHours);
void QWallet611006_ConnectCoinHoursChanged(void* ptr);
void QWallet611006_DisconnectCoinHoursChanged(void* ptr);
void QWallet611006_CoinHoursChanged(void* ptr, int coinHours);
struct Moc_PackedString QWallet611006_FileName(void* ptr);
struct Moc_PackedString QWallet611006_FileNameDefault(void* ptr);
void QWallet611006_SetFileName(void* ptr, struct Moc_PackedString fileName);
void QWallet611006_SetFileNameDefault(void* ptr, struct Moc_PackedString fileName);
void QWallet611006_ConnectFileNameChanged(void* ptr);
void QWallet611006_DisconnectFileNameChanged(void* ptr);
void QWallet611006_FileNameChanged(void* ptr, struct Moc_PackedString fileName);
int QWallet611006_QWallet611006_QRegisterMetaType();
int QWallet611006_QWallet611006_QRegisterMetaType2(char* typeName);
int QWallet611006_QWallet611006_QmlRegisterType();
int QWallet611006_QWallet611006_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
void* QWallet611006___children_atList(void* ptr, int i);
void QWallet611006___children_setList(void* ptr, void* i);
void* QWallet611006___children_newList(void* ptr);
void* QWallet611006___dynamicPropertyNames_atList(void* ptr, int i);
void QWallet611006___dynamicPropertyNames_setList(void* ptr, void* i);
void* QWallet611006___dynamicPropertyNames_newList(void* ptr);
void* QWallet611006___findChildren_atList(void* ptr, int i);
void QWallet611006___findChildren_setList(void* ptr, void* i);
void* QWallet611006___findChildren_newList(void* ptr);
void* QWallet611006___findChildren_atList3(void* ptr, int i);
void QWallet611006___findChildren_setList3(void* ptr, void* i);
void* QWallet611006___findChildren_newList3(void* ptr);
void* QWallet611006___qFindChildren_atList2(void* ptr, int i);
void QWallet611006___qFindChildren_setList2(void* ptr, void* i);
void* QWallet611006___qFindChildren_newList2(void* ptr);
void* QWallet611006_NewQWallet(void* parent);
void QWallet611006_DestroyQWallet(void* ptr);
void QWallet611006_DestroyQWalletDefault(void* ptr);
void QWallet611006_ChildEventDefault(void* ptr, void* event);
void QWallet611006_ConnectNotifyDefault(void* ptr, void* sign);
void QWallet611006_CustomEventDefault(void* ptr, void* event);
void QWallet611006_DeleteLaterDefault(void* ptr);
void QWallet611006_DisconnectNotifyDefault(void* ptr, void* sign);
char QWallet611006_EventDefault(void* ptr, void* e);
char QWallet611006_EventFilterDefault(void* ptr, void* watched, void* event);
void QWallet611006_TimerEventDefault(void* ptr, void* event);
void WalletManager611006_CreateEncryptedWallet(void* ptr, void* walletM, struct Moc_PackedString seed, struct Moc_PackedString label, struct Moc_PackedString password, int scanN);
void WalletManager611006_CreateUnencryptedWallet(void* ptr, void* walletM, struct Moc_PackedString seed, struct Moc_PackedString label, int scanN);
struct Moc_PackedString WalletManager611006_GetNewSeed(void* ptr, int entropy);
int WalletManager611006_VerifySeed(void* ptr, struct Moc_PackedString seed);
void WalletManager611006_NewWalletAddress(void* ptr, void* addressM, struct Moc_PackedString id, int n, struct Moc_PackedString password);
void WalletManager611006_EncryptWallet(void* ptr, void* walletM, struct Moc_PackedString id, struct Moc_PackedString password);
void WalletManager611006_DecryptWallet(void* ptr, void* walletM, struct Moc_PackedString id, struct Moc_PackedString password);
int WalletManager611006_WalletManager611006_QRegisterMetaType();
int WalletManager611006_WalletManager611006_QRegisterMetaType2(char* typeName);
int WalletManager611006_WalletManager611006_QmlRegisterType();
int WalletManager611006_WalletManager611006_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
void* WalletManager611006___children_atList(void* ptr, int i);
void WalletManager611006___children_setList(void* ptr, void* i);
void* WalletManager611006___children_newList(void* ptr);
void* WalletManager611006___dynamicPropertyNames_atList(void* ptr, int i);
void WalletManager611006___dynamicPropertyNames_setList(void* ptr, void* i);
void* WalletManager611006___dynamicPropertyNames_newList(void* ptr);
void* WalletManager611006___findChildren_atList(void* ptr, int i);
void WalletManager611006___findChildren_setList(void* ptr, void* i);
void* WalletManager611006___findChildren_newList(void* ptr);
void* WalletManager611006___findChildren_atList3(void* ptr, int i);
void WalletManager611006___findChildren_setList3(void* ptr, void* i);
void* WalletManager611006___findChildren_newList3(void* ptr);
void* WalletManager611006___qFindChildren_atList2(void* ptr, int i);
void WalletManager611006___qFindChildren_setList2(void* ptr, void* i);
void* WalletManager611006___qFindChildren_newList2(void* ptr);
void* WalletManager611006_NewWalletManager(void* parent);
void WalletManager611006_DestroyWalletManager(void* ptr);
void WalletManager611006_DestroyWalletManagerDefault(void* ptr);
void WalletManager611006_ChildEventDefault(void* ptr, void* event);
void WalletManager611006_ConnectNotifyDefault(void* ptr, void* sign);
void WalletManager611006_CustomEventDefault(void* ptr, void* event);
void WalletManager611006_DeleteLaterDefault(void* ptr);
void WalletManager611006_DisconnectNotifyDefault(void* ptr, void* sign);
char WalletManager611006_EventDefault(void* ptr, void* e);
char WalletManager611006_EventFilterDefault(void* ptr, void* watched, void* event);
void WalletManager611006_TimerEventDefault(void* ptr, void* event);
void WalletModel611006_AddWallet(void* ptr, void* v0);
void WalletModel611006_EditWallet(void* ptr, int row, struct Moc_PackedString name, char encryptionEnabled, int sky, int coinHours);
void WalletModel611006_RemoveWallet(void* ptr, int row);
void WalletModel611006_LoadModel(void* ptr);
struct Moc_PackedList WalletModel611006_Roles(void* ptr);
struct Moc_PackedList WalletModel611006_RolesDefault(void* ptr);
void WalletModel611006_SetRoles(void* ptr, void* roles);
void WalletModel611006_SetRolesDefault(void* ptr, void* roles);
void WalletModel611006_ConnectRolesChanged(void* ptr);
void WalletModel611006_DisconnectRolesChanged(void* ptr);
void WalletModel611006_RolesChanged(void* ptr, void* roles);
struct Moc_PackedList WalletModel611006_Wallets(void* ptr);
struct Moc_PackedList WalletModel611006_WalletsDefault(void* ptr);
void WalletModel611006_SetWallets(void* ptr, void* wallets);
void WalletModel611006_SetWalletsDefault(void* ptr, void* wallets);
void WalletModel611006_ConnectWalletsChanged(void* ptr);
void WalletModel611006_DisconnectWalletsChanged(void* ptr);
void WalletModel611006_WalletsChanged(void* ptr, void* wallets);
int WalletModel611006_WalletModel611006_QRegisterMetaType();
int WalletModel611006_WalletModel611006_QRegisterMetaType2(char* typeName);
int WalletModel611006_WalletModel611006_QmlRegisterType();
int WalletModel611006_WalletModel611006_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
int WalletModel611006_____itemData_keyList_atList(void* ptr, int i);
void WalletModel611006_____itemData_keyList_setList(void* ptr, int i);
void* WalletModel611006_____itemData_keyList_newList(void* ptr);
int WalletModel611006_____roleNames_keyList_atList(void* ptr, int i);
void WalletModel611006_____roleNames_keyList_setList(void* ptr, int i);
void* WalletModel611006_____roleNames_keyList_newList(void* ptr);
int WalletModel611006_____setItemData_roles_keyList_atList(void* ptr, int i);
void WalletModel611006_____setItemData_roles_keyList_setList(void* ptr, int i);
void* WalletModel611006_____setItemData_roles_keyList_newList(void* ptr);
void* WalletModel611006___changePersistentIndexList_from_atList(void* ptr, int i);
void WalletModel611006___changePersistentIndexList_from_setList(void* ptr, void* i);
void* WalletModel611006___changePersistentIndexList_from_newList(void* ptr);
void* WalletModel611006___changePersistentIndexList_to_atList(void* ptr, int i);
void WalletModel611006___changePersistentIndexList_to_setList(void* ptr, void* i);
void* WalletModel611006___changePersistentIndexList_to_newList(void* ptr);
int WalletModel611006___dataChanged_roles_atList(void* ptr, int i);
void WalletModel611006___dataChanged_roles_setList(void* ptr, int i);
void* WalletModel611006___dataChanged_roles_newList(void* ptr);
void* WalletModel611006___itemData_atList(void* ptr, int v, int i);
void WalletModel611006___itemData_setList(void* ptr, int key, void* i);
void* WalletModel611006___itemData_newList(void* ptr);
struct Moc_PackedList WalletModel611006___itemData_keyList(void* ptr);
void* WalletModel611006___layoutAboutToBeChanged_parents_atList(void* ptr, int i);
void WalletModel611006___layoutAboutToBeChanged_parents_setList(void* ptr, void* i);
void* WalletModel611006___layoutAboutToBeChanged_parents_newList(void* ptr);
void* WalletModel611006___layoutChanged_parents_atList(void* ptr, int i);
void WalletModel611006___layoutChanged_parents_setList(void* ptr, void* i);
void* WalletModel611006___layoutChanged_parents_newList(void* ptr);
void* WalletModel611006___match_atList(void* ptr, int i);
void WalletModel611006___match_setList(void* ptr, void* i);
void* WalletModel611006___match_newList(void* ptr);
void* WalletModel611006___mimeData_indexes_atList(void* ptr, int i);
void WalletModel611006___mimeData_indexes_setList(void* ptr, void* i);
void* WalletModel611006___mimeData_indexes_newList(void* ptr);
void* WalletModel611006___persistentIndexList_atList(void* ptr, int i);
void WalletModel611006___persistentIndexList_setList(void* ptr, void* i);
void* WalletModel611006___persistentIndexList_newList(void* ptr);
void* WalletModel611006___roleNames_atList(void* ptr, int v, int i);
void WalletModel611006___roleNames_setList(void* ptr, int key, void* i);
void* WalletModel611006___roleNames_newList(void* ptr);
struct Moc_PackedList WalletModel611006___roleNames_keyList(void* ptr);
void* WalletModel611006___setItemData_roles_atList(void* ptr, int v, int i);
void WalletModel611006___setItemData_roles_setList(void* ptr, int key, void* i);
void* WalletModel611006___setItemData_roles_newList(void* ptr);
struct Moc_PackedList WalletModel611006___setItemData_roles_keyList(void* ptr);
int WalletModel611006_____doSetRoleNames_roleNames_keyList_atList(void* ptr, int i);
void WalletModel611006_____doSetRoleNames_roleNames_keyList_setList(void* ptr, int i);
void* WalletModel611006_____doSetRoleNames_roleNames_keyList_newList(void* ptr);
int WalletModel611006_____setRoleNames_roleNames_keyList_atList(void* ptr, int i);
void WalletModel611006_____setRoleNames_roleNames_keyList_setList(void* ptr, int i);
void* WalletModel611006_____setRoleNames_roleNames_keyList_newList(void* ptr);
void* WalletModel611006___children_atList(void* ptr, int i);
void WalletModel611006___children_setList(void* ptr, void* i);
void* WalletModel611006___children_newList(void* ptr);
void* WalletModel611006___dynamicPropertyNames_atList(void* ptr, int i);
void WalletModel611006___dynamicPropertyNames_setList(void* ptr, void* i);
void* WalletModel611006___dynamicPropertyNames_newList(void* ptr);
void* WalletModel611006___findChildren_atList(void* ptr, int i);
void WalletModel611006___findChildren_setList(void* ptr, void* i);
void* WalletModel611006___findChildren_newList(void* ptr);
void* WalletModel611006___findChildren_atList3(void* ptr, int i);
void WalletModel611006___findChildren_setList3(void* ptr, void* i);
void* WalletModel611006___findChildren_newList3(void* ptr);
void* WalletModel611006___qFindChildren_atList2(void* ptr, int i);
void WalletModel611006___qFindChildren_setList2(void* ptr, void* i);
void* WalletModel611006___qFindChildren_newList2(void* ptr);
void* WalletModel611006___roles_atList(void* ptr, int v, int i);
void WalletModel611006___roles_setList(void* ptr, int key, void* i);
void* WalletModel611006___roles_newList(void* ptr);
struct Moc_PackedList WalletModel611006___roles_keyList(void* ptr);
void* WalletModel611006___setRoles_roles_atList(void* ptr, int v, int i);
void WalletModel611006___setRoles_roles_setList(void* ptr, int key, void* i);
void* WalletModel611006___setRoles_roles_newList(void* ptr);
struct Moc_PackedList WalletModel611006___setRoles_roles_keyList(void* ptr);
void* WalletModel611006___rolesChanged_roles_atList(void* ptr, int v, int i);
void WalletModel611006___rolesChanged_roles_setList(void* ptr, int key, void* i);
void* WalletModel611006___rolesChanged_roles_newList(void* ptr);
struct Moc_PackedList WalletModel611006___rolesChanged_roles_keyList(void* ptr);
void* WalletModel611006___wallets_atList(void* ptr, int i);
void WalletModel611006___wallets_setList(void* ptr, void* i);
void* WalletModel611006___wallets_newList(void* ptr);
void* WalletModel611006___setWallets_wallets_atList(void* ptr, int i);
void WalletModel611006___setWallets_wallets_setList(void* ptr, void* i);
void* WalletModel611006___setWallets_wallets_newList(void* ptr);
void* WalletModel611006___walletsChanged_wallets_atList(void* ptr, int i);
void WalletModel611006___walletsChanged_wallets_setList(void* ptr, void* i);
void* WalletModel611006___walletsChanged_wallets_newList(void* ptr);
int WalletModel611006_____roles_keyList_atList(void* ptr, int i);
void WalletModel611006_____roles_keyList_setList(void* ptr, int i);
void* WalletModel611006_____roles_keyList_newList(void* ptr);
int WalletModel611006_____setRoles_roles_keyList_atList(void* ptr, int i);
void WalletModel611006_____setRoles_roles_keyList_setList(void* ptr, int i);
void* WalletModel611006_____setRoles_roles_keyList_newList(void* ptr);
int WalletModel611006_____rolesChanged_roles_keyList_atList(void* ptr, int i);
void WalletModel611006_____rolesChanged_roles_keyList_setList(void* ptr, int i);
void* WalletModel611006_____rolesChanged_roles_keyList_newList(void* ptr);
void* WalletModel611006_NewWalletModel(void* parent);
void WalletModel611006_DestroyWalletModel(void* ptr);
void WalletModel611006_DestroyWalletModelDefault(void* ptr);
char WalletModel611006_DropMimeDataDefault(void* ptr, void* data, long long action, int row, int column, void* parent);
long long WalletModel611006_FlagsDefault(void* ptr, void* index);
void* WalletModel611006_IndexDefault(void* ptr, int row, int column, void* parent);
void* WalletModel611006_SiblingDefault(void* ptr, int row, int column, void* idx);
void* WalletModel611006_BuddyDefault(void* ptr, void* index);
char WalletModel611006_CanDropMimeDataDefault(void* ptr, void* data, long long action, int row, int column, void* parent);
char WalletModel611006_CanFetchMoreDefault(void* ptr, void* parent);
int WalletModel611006_ColumnCountDefault(void* ptr, void* parent);
void* WalletModel611006_DataDefault(void* ptr, void* index, int role);
void WalletModel611006_FetchMoreDefault(void* ptr, void* parent);
char WalletModel611006_HasChildrenDefault(void* ptr, void* parent);
void* WalletModel611006_HeaderDataDefault(void* ptr, int section, long long orientation, int role);
char WalletModel611006_InsertColumnsDefault(void* ptr, int column, int count, void* parent);
char WalletModel611006_InsertRowsDefault(void* ptr, int row, int count, void* parent);
struct Moc_PackedList WalletModel611006_ItemDataDefault(void* ptr, void* index);
struct Moc_PackedList WalletModel611006_MatchDefault(void* ptr, void* start, int role, void* value, int hits, long long flags);
void* WalletModel611006_MimeDataDefault(void* ptr, void* indexes);
struct Moc_PackedString WalletModel611006_MimeTypesDefault(void* ptr);
char WalletModel611006_MoveColumnsDefault(void* ptr, void* sourceParent, int sourceColumn, int count, void* destinationParent, int destinationChild);
char WalletModel611006_MoveRowsDefault(void* ptr, void* sourceParent, int sourceRow, int count, void* destinationParent, int destinationChild);
void* WalletModel611006_ParentDefault(void* ptr, void* index);
char WalletModel611006_RemoveColumnsDefault(void* ptr, int column, int count, void* parent);
char WalletModel611006_RemoveRowsDefault(void* ptr, int row, int count, void* parent);
void WalletModel611006_ResetInternalDataDefault(void* ptr);
void WalletModel611006_RevertDefault(void* ptr);
struct Moc_PackedList WalletModel611006_RoleNamesDefault(void* ptr);
int WalletModel611006_RowCountDefault(void* ptr, void* parent);
char WalletModel611006_SetDataDefault(void* ptr, void* index, void* value, int role);
char WalletModel611006_SetHeaderDataDefault(void* ptr, int section, long long orientation, void* value, int role);
char WalletModel611006_SetItemDataDefault(void* ptr, void* index, void* roles);
void WalletModel611006_SortDefault(void* ptr, int column, long long order);
void* WalletModel611006_SpanDefault(void* ptr, void* index);
char WalletModel611006_SubmitDefault(void* ptr);
long long WalletModel611006_SupportedDragActionsDefault(void* ptr);
long long WalletModel611006_SupportedDropActionsDefault(void* ptr);
void WalletModel611006_ChildEventDefault(void* ptr, void* event);
void WalletModel611006_ConnectNotifyDefault(void* ptr, void* sign);
void WalletModel611006_CustomEventDefault(void* ptr, void* event);
void WalletModel611006_DeleteLaterDefault(void* ptr);
void WalletModel611006_DisconnectNotifyDefault(void* ptr, void* sign);
char WalletModel611006_EventDefault(void* ptr, void* e);
char WalletModel611006_EventFilterDefault(void* ptr, void* watched, void* event);
void WalletModel611006_TimerEventDefault(void* ptr, void* event);

#ifdef __cplusplus
}
#endif

#endif