// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import core "github.com/fibercrypto/fibercryptowallet/src/core"
import mock "github.com/stretchr/testify/mock"

// Address is an autogenerated mock type for the Address type
type Address struct {
	mock.Mock
}

// GetCryptoAccount provides a mock function with given fields:
func (_m *Address) GetCryptoAccount() core.CryptoAccount {
	ret := _m.Called()

	var r0 core.CryptoAccount
	if rf, ok := ret.Get(0).(func() core.CryptoAccount); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.CryptoAccount)
		}
	}

	return r0
}

// IsBip32 provides a mock function with given fields:
func (_m *Address) IsBip32() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// String provides a mock function with given fields:
func (_m *Address) String() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
