// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MultiPoolSection is an autogenerated mock type for the MultiPoolSection type
type MultiPoolSection struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *MultiPoolSection) Get() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// Put provides a mock function with given fields: _a0
func (_m *MultiPoolSection) Put(_a0 interface{}) {
	_m.Called(_a0)
}
