// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import core "github.com/fibercrypto/fibercryptowallet/src/core"
import mock "github.com/stretchr/testify/mock"

// PexNodeIterator is an autogenerated mock type for the PexNodeIterator type
type PexNodeIterator struct {
	mock.Mock
}

// HasNext provides a mock function with given fields:
func (_m *PexNodeIterator) HasNext() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Next provides a mock function with given fields:
func (_m *PexNodeIterator) Next() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Value provides a mock function with given fields:
func (_m *PexNodeIterator) Value() core.PexNode {
	ret := _m.Called()

	var r0 core.PexNode
	if rf, ok := ret.Get(0).(func() core.PexNode); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.PexNode)
		}
	}

	return r0
}
