// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SeedGenerator is an autogenerated mock type for the SeedGenerator type
type SeedGenerator struct {
	mock.Mock
}

// GenerateMnemonic provides a mock function with given fields: wordCount
func (_m *SeedGenerator) GenerateMnemonic(wordCount int) (string, error) {
	ret := _m.Called(wordCount)

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(wordCount)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(wordCount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyMnemonic provides a mock function with given fields: seed
func (_m *SeedGenerator) VerifyMnemonic(seed string) (bool, error) {
	ret := _m.Called(seed)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(seed)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(seed)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
