// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import core "github.com/fibercrypto/FiberCryptoWallet/src/core"
import mock "github.com/stretchr/testify/mock"

// WalletEnv is an autogenerated mock type for the WalletEnv type
type WalletEnv struct {
	mock.Mock
}

// GetStorage provides a mock function with given fields:
func (_m *WalletEnv) GetStorage() core.WalletStorage {
	ret := _m.Called()

	var r0 core.WalletStorage
	if rf, ok := ret.Get(0).(func() core.WalletStorage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.WalletStorage)
		}
	}

	return r0
}

// GetWalletSet provides a mock function with given fields:
func (_m *WalletEnv) GetWalletSet() core.WalletSet {
	ret := _m.Called()

	var r0 core.WalletSet
	if rf, ok := ret.Get(0).(func() core.WalletSet); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.WalletSet)
		}
	}

	return r0
}
