// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import core "github.com/fibercrypto/fibercryptowallet/src/core"
import mock "github.com/stretchr/testify/mock"

// WalletAddress is an autogenerated mock type for the WalletAddress type
type WalletAddress struct {
	mock.Mock
}

// GetAddress provides a mock function with given fields:
func (_m *WalletAddress) GetAddress() core.Address {
	ret := _m.Called()

	var r0 core.Address
	if rf, ok := ret.Get(0).(func() core.Address); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Address)
		}
	}

	return r0
}

// GetWallet provides a mock function with given fields:
func (_m *WalletAddress) GetWallet() core.Wallet {
	ret := _m.Called()

	var r0 core.Wallet
	if rf, ok := ret.Get(0).(func() core.Wallet); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Wallet)
		}
	}

	return r0
}
