// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import core "github.com/fibercrypto/fibercryptowallet/src/core"
import mock "github.com/stretchr/testify/mock"

// WalletEnv is an autogenerated mock type for the WalletEnv type
type WalletEnv struct {
	mock.Mock
}

// GetStorage provides a mock function with given fields:
func (_m *WalletEnv) GetStorage() core.WalletStorage {
	ret := _m.Called()

	var r0 core.WalletStorage
	if rf, ok := ret.Get(0).(func() core.WalletStorage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.WalletStorage)
		}
	}

	return r0
}

// GetWallet provides a mock function with given fields: firstAddr
func (_m *WalletEnv) GetWallet(firstAddr string) (core.Wallet, error) {
	ret := _m.Called(firstAddr)

	var r0 core.Wallet
	if rf, ok := ret.Get(0).(func(string) core.Wallet); ok {
		r0 = rf(firstAddr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Wallet)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(firstAddr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWalletSet provides a mock function with given fields:
func (_m *WalletEnv) GetWalletSet() core.WalletSet {
	ret := _m.Called()

	var r0 core.WalletSet
	if rf, ok := ret.Get(0).(func() core.WalletSet); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.WalletSet)
		}
	}

	return r0
}
