// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import skywallet "github.com/fibercrypto/skywallet-go/src/skywallet"
import usb "github.com/fibercrypto/skywallet-go/src/skywallet/usb"
import wire "github.com/fibercrypto/skywallet-go/src/skywallet/wire"

// DeviceDriver is an autogenerated mock type for the DeviceDriver type
type DeviceDriver struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *DeviceDriver) Close() {
	_m.Called()
}

// DeviceType provides a mock function with given fields:
func (_m *DeviceDriver) DeviceType() skywallet.DeviceType {
	ret := _m.Called()

	var r0 skywallet.DeviceType
	if rf, ok := ret.Get(0).(func() skywallet.DeviceType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(skywallet.DeviceType)
	}

	return r0
}

// GetDevice provides a mock function with given fields:
func (_m *DeviceDriver) GetDevice() (usb.Device, error) {
	ret := _m.Called()

	var r0 usb.Device
	if rf, ok := ret.Get(0).(func() usb.Device); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(usb.Device)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDeviceInfos provides a mock function with given fields:
func (_m *DeviceDriver) GetDeviceInfos() ([]usb.Info, error) {
	ret := _m.Called()

	var r0 []usb.Info
	if rf, ok := ret.Get(0).(func() []usb.Info); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]usb.Info)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendToDevice provides a mock function with given fields: dev, chunks
func (_m *DeviceDriver) SendToDevice(dev usb.Device, chunks [][64]byte) (wire.Message, error) {
	ret := _m.Called(dev, chunks)

	var r0 wire.Message
	if rf, ok := ret.Get(0).(func(usb.Device, [][64]byte) wire.Message); ok {
		r0 = rf(dev, chunks)
	} else {
		r0 = ret.Get(0).(wire.Message)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(usb.Device, [][64]byte) error); ok {
		r1 = rf(dev, chunks)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendToDeviceNoAnswer provides a mock function with given fields: dev, chunks
func (_m *DeviceDriver) SendToDeviceNoAnswer(dev usb.Device, chunks [][64]byte) error {
	ret := _m.Called(dev, chunks)

	var r0 error
	if rf, ok := ret.Get(0).(func(usb.Device, [][64]byte) error); ok {
		r0 = rf(dev, chunks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
